### ISSUE TITLE
Impedir Agente Padrão de criar entidades com status = 0

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#108]
Atualmente a plataforma está permitindo que o agente padrão crie entidades na plataforma sem estar com seu status de publicação definido como "Publicado". Isso ocasiona o fato de que ao tentar acessar a página de quem criou a entidade gera um link quebrado: Página não encontrada" 
Agente padrão: http://mapas.cultura.gov.br/agente/21395
Entidade criada pelo mesmo: http://mapas.cultura.gov.br/agente/21956

Essa situação também impede de associar esse agente a administração de objetos na plataforma, como subsites por exemplo.

**Comment by marcus2703** [comment]
@marcus2703 verificar se a correção quebra o Cultura Viva em casos do agente já existente.

**Comment by leogermani** [comment]
Qual o status dessa issue?

**Comment by marcus2703** [comment]
Então @leogermani, o Rafa já fez uma alteração que impede o usuário de conseguir fazer cadastros de entidades estando com o status do agente padrão como rascunho. Ele sempre carrega a página da edição do agente para concluir o cadastro.
