### ISSUE TITLE
Notificações no tema de Bibliotecas

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#109]
No painel de bibliotecas estão aparecendo várias notificações desnecessárias e a equipe quer que apareçam somente as notificações de permissão, conforme está configurado no tema dos museus.

![image001](https://user-images.githubusercontent.com/18294515/30702702-01659c9c-9ec4-11e7-9fd5-a6820b09d3e4.jpg)

Recuperamos o script para resolver esse problema das notificações. 
Tem que trocar o [user_id] pelo id do usuário que quer deletar as notificações, mas o @marcus2703 testou e mesmo removendo as notificações, ao tentar acessar o sistema, começa a recriar as mesmas notificações.

```
delete from
    notification
where id in (
    select
        n.id    
    from
        notification n
            left join request r
            on n.request_id = r.id
    where
        r.id is null
        and n.user_id = [user_id]
);
```

**Comment by leogermani** [comment]
O usuário da DLLLB é 300021

**Comment by leogermani** [comment]
https://github.com/culturagovbr/mapasculturais-bibliotecas/commit/46ea7b4bc8ec640e5f23df4a66b02fc887cf339b
