### ISSUE TITLE
Imagens para perfil Edital

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#112]
- [x] Imagem para capa da página do Edital
- [x] Imagem do edital (perfil)

**Comment by moisesrlima** [comment]
![credenciamento-parecerista2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a147b27364f450011f372b3/125516c66e82c728ace21e0d46eb869f27878daa86e8b246aa49ffd9394735762a01b1226391e27afd0e39111d0014f9121c4d4eeefc8f28f2b66822890e5ebfd46f0974903d11a9b1871fba00a83c990dd4e8e8d51199a26867f5819d4e3614041d88fe5f3ca19e4dc05ff04bf300.png)

**Comment by moisesrlima** [comment]
[Uploading logo.png...]

**Comment by moisesrlima** [comment]
![Frame (2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a147b27364f450011f372b3/125516c66e82c728ace21e0d46ce869b2e87c3e1dda0fd0fe64de29b234324676b5ee17e26d6e778bb4028030a0d4bae17580944fcfc802ea6b33d62964e49bc8f3900299f7744eeaa880dbe06b0218e4e84b4b5884dc2ea3423e399c2.png)

**Comment by moisesrlima** [comment]
![Frame-(2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a147b27364f450011f372b3/125516c66e82c728ace21e0d46ce869b2e87cee1dda0fd0fe64de29b234324676b5ee17e26d6e778bb4028030a0d4bae17580944fcfc802ea6b33d62964e49bc8f3900299f7744eeaa880dbe09b0218e4e84b4b5884fc1e13a2cef99c2.png)

**Comment by moisesrlima** [comment]
![logo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a147b27364f450011f372b3/125516c66e82c728ace21e0d46e49b9d2cc0cfeb9ffbb049a15ee4d6730472257a00f32f72d6e12dbd1729075f094eac44515a44f9f89b37b4f46d2ede0356b49b381d66cc2f10abb2831abe00b829894a8cb6b48f44d2a5.png)

**Comment by moisesrlima** [comment]
![credenciamento-parecerista2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a147b27364f450011f372b3/125516c66e82c728ace21e0d46eb869f27878daa86e8b246aa49ffd9394735762a01b1226391e27afd0e39111d0014f9121c4d4eeefc8f28f2b66822890e5ebfd46f0974903d11a9b1871fba00a83c990dd4e8e8d51199a26867f5819d4e3714041d88fe5f3ca49b4fca51f64af300.png)

**Comment by moisesrlima** [comment]
![megaphone.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a147b27364f450011f372b3/125516c66e82c728ace21e0d46e5919d22928ba681ecfd0fe64de29b234324676b5ee17e26d6e778bb4028030a0d4bae17580944fcfc802ea6b33d62964e49bc8f3900299f7744eeaa880dbe09b0218e4e84b4b58e4bc0ea3b27e799c2.png)  

ícone para editais

**Comment by moisesrlima** [comment]
Cor para editais: #388784

**Comment by Pedro-Philipe** [comment]
Os ícone foi atualizado diferente do que o @moisesrlima tinha dito inicialmente sobre o megafone, devido a não existencia do mesmo nas bibliotecas do core do mapas. Eu e @moisesrlima conversamos e escolher um que atenda a idéia sem ficar tão parecido com a entidade projetos.
![image](https://user-images.githubusercontent.com/15365573/33143720-e28d5800-cfa1-11e7-8830-77c361ecc7e9.png)
