### ISSUE TITLE
Correção de bug no filtro por tipo do tema de Bibliotecas

### ISSUE THREAD

**Issue by GustavoVS** [culturagovbr/mapasculturais_descontinuado#118]
O filtro por tipo não tem efeito nos resultados exibidos no mapa

![image](https://user-images.githubusercontent.com/7750643/35638013-13579a36-069d-11e8-957c-9fbb398d0391.png)

![image](https://user-images.githubusercontent.com/7750643/35638027-200de05a-069d-11e8-9f7a-c75547a25c0a.png)

**Comment by GustavoVS** [comment]
Corrigido nos commit

https://github.com/culturagovbr/mapasculturais/commit/114b4645581c56d1592e40cba703c32e092f927c
https://github.com/culturagovbr/mapasculturais-bibliotecas/commit/99b759fbaa74bcaa13aa036ebb087d0ecc58806d

Disponível no ambiente de testes http://bibliotecas.dev.saas.mapas.cultura.gov.br/

![image](https://user-images.githubusercontent.com/7750643/35988512-bd56973c-0ce5-11e8-9e6c-674916ce372d.png)

**Comment by GustavoVS** [comment]
@marcus2703 para que o filtro funcione corretamente também é necessário configurar os tipos de bibliotecas a serem exibidos no Mapas (dentro do painel do Subsite)

![image](https://user-images.githubusercontent.com/7750643/35988676-49c30c96-0ce6-11e8-8c0b-f92c19bca9c5.png)

**Comment by marcus2703** [comment]
Testado.
Podemos colocar em produção

@leogermani vamos criar TAG ou usar a master mesmo?

**Comment by marcus2703** [comment]
Atualizado na Master
