### ISSUE TITLE
BUG: validação do campo tipologia de agentes

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#12]
Quando não valida, aparece uma vaidação flutuando com um input text misterioso

**Comment by marcus2703** [comment]
O erro acima é corrigido com o comit https://github.com/culturagovbr/mapasculturais/commit/ad32acff2ec37406d70671e0a713e8f5c1c838ea

Já testamos aqui no MinC, funcionou. Falta realizar PR no repo Hacklab

@leogermani
