### ISSUE TITLE
Arrumar ordem das informações na Edição de Oportunidades

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#130]
Na branch de oportunidades, a tela de edição da oportunidade mudou um tanto a ordenação das seções, deixando o formulário um pouco confuso.

Por exemplo, a parte de Importar e Exportar o formulário está no meio de tudo. As categorias do edital, que são informações que deveriam estar no começo, estão no fim, e etc.

Essa issue tem duas subtarefas:

- [x] Arrumar a ordem dessas seções na página, de maneira que fique assim:

* Introdução
* Regulamento
* Vídeos e Galeria
* Opções
* Agentes
* Campos
* Formulário para Recurso
* Importar/Exportar

- [x] Deixar o campo Importar/Exportar, que é o último, com um comportamento de sanfona. Ou seja, aparece só o tíulo e vc abre ou fecha os detlahes dele clicando em cima

Seria legal se @rafaelchavesfreitas, @Pedro-Philipe e @Andreqlp pudessem confirmar que essa issue faz sentido.

**Comment by Andreqlp** [comment]
Concordo, só faria uma pequena mudança na ordem apresentada. Colocaria primeiro os "Agentes" e depois as "Opções", pois o campo opções se relaciona diretamente com os campos de perguntas.

**Comment by r-guimaraes** [comment]
Feito
