### ISSUE TITLE
Busca por ID da inscrição

### ISSUE THREAD

**Issue by Pedro-Philipe** [culturagovbr/mapasculturais_descontinuado#134]
Filtro de buscar pelo id da inscrição na aba de inscritos

**Comment by Andreqlp** [comment]
Como foi criado um campo específico para o nome do projeto, na ficha de inscrição, seria ótimo conseguir visualizar esse campo na aba de inscritos. O gerente do projeto e os avaliadores costumam lembrar principalmente desse campo, ao invés do número ou do nome do inscrito.
