### ISSUE TITLE
Redirect após login

### ISSUE THREAD

**Issue by r-guimaraes** [culturagovbr/mapasculturais_descontinuado#143]
Após clicar para realizar o login, manter o usuário na mesma página onde estava navegando anteriormente

**Comment by leogermani** [comment]
esse commit tb é dessa issue https://github.com/culturagovbr/mapasculturais/commit/113052e4e3eaadb1c889ff87be1a7700638f95fc

**Comment by leogermani** [comment]
Não está funcionando como esperado...
