### ISSUE TITLE
Hash das tabs não funcionam ao acessar a url

### ISSUE THREAD

**Issue by asaferamos** [culturagovbr/mapasculturais_descontinuado#144]
As urls com hash, utulizado pelas abas no tema, não funcioam.
Exemplo:
A url abaixo não exibe a tab Público, mas sim, a tab Sobre
`http://museus.mapas.minc/espaco/8128/#/tab=tab-publico`

**Comment by leogermani** [comment]
Asafe, vi um comportamento estranho aqui que talvez esteja relacionado a isso.

Quando entrei na página de uma oportunidade, sem nenhuma aba selecionada, a página ficou sem conteúdo. O conteúdo só apareceu quando eu cliquei na primeira aba, a "Principal".

Não vi aconecendo em outras entidades. Pode checar se tem relação com o q vc fez?

**Comment by asaferamos** [comment]
Tem relação sim, e corrigi [aqui](https://github.com/culturagovbr/mapasculturais/commit/a0d8540e394c4242cfb359c600efc7920df3916c).

**Comment by leogermani** [comment]
https://github.com/culturagovbr/mapasculturais/commit/2b4d4e348a0b4180e6e1de3522ea8c516be73791
