### ISSUE TITLE
Criar filtro de selos

### ISSUE THREAD

**Issue by marylly** [culturagovbr/mapasculturais_descontinuado#15]
Criar featured de filtro de entidades utilizando a informação dos selos na nova estrutura do sistema.

**Comment by marylly** [comment]
Essa feature foi contemplada na implementação da nova estrutura de selos para os filtro de registros verificados? @GustavoVS @robertkapa @rafaelchavesfreitas

**Comment by thaisrigolon** [comment]
Sim, está contemplado. Pode fechar a issue.
