### ISSUE TITLE
Link "Meu Perfil" no painel

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#151]
Tirar Agente padrão da listagem de agentes e cirar o item Meu Perfil no painel, igual tem no IBRAM

**Comment by asaferamos** [comment]
Resolvido [aqui](https://github.com/culturagovbr/mapasculturais/commit/625b21a6590d153a56115a06ad6e8696b18c81ad). Branch _feature/menuMeuPerfil_

**Comment by leogermani** [comment]
não consegui validar. 

Não apareceu o item Meu perfil no menu (nem na esquerda nem no dropdown do topo)

Na listagem de agentes, apesar de o agente padrão ter sumido dali, a contagem que aparece ao lado do nome ainda conta com ele 

"Ativos (1)"

Acho que se a pessoa não tiver nenhum outro agente além do padrão, pode ter algum link para o meu perfil ali também.. vamos avaliar um pouco melhor pra não gerar confusão
