### ISSUE TITLE
Redirect do logout manda pra tela de logout do ID Cultura

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#153]

**Comment by asaferamos** [comment]
[Commit](https://github.com/culturagovbr/mapasculturais/commit/691f44417f8267a504f15ae83a6fa0911979b8d4)

**Comment by leogermani** [comment]
Conferir se a configuração no painel do ID Cultura está certa

**Comment by r-guimaraes** [comment]
É necessário alterar o arquivo **/mapasculturais/src/protected/application/conf/config.php**,
adicionando a seguinte entrada no array da chave "auth.config":

``'logout_url' => 'https://id.cultura.gov.br/logout'``

**Comment by leogermani** [comment]
Ainda falta fazer a configuração em produção

**Comment by marcus2703** [comment]
Atualizado em 31/07.
Ao selecionar a opção "Sair" o Mapas encaminha para o logout do ID Cultura, permanecendo na tela do ID.
