### ISSUE TITLE
Painel admin: gestão de usuários

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#160]
Buscar usuários (agentes padrão) e ver tudo dele
O q ele publicou
O q ele tem concessão
Mudar status..
Mudar email…
Mudar papel

**Comment by leogermani** [comment]
Buscar por agente (qq um), espaço, projeto etc

vai achar as entidades e mostrar, quando clicar, a tela do usuário

Tela do usuário mostra
. De que site o cara veio
. dados da tabela de usuário (email, id, modo de autenticação, id no servidor de autenticação)
. agente padrão
. todos os agentes
. todas as entidades q ele publicou
. todas as entidades q ele tem controle

Permite mudar o Role dele

arquivar, apagar, restaurar as entidades do usuário

link pra editar as entidades do usuário

mudar o agente do padrão do usuário

Pro futuro: cada modo de autenticação poder ter opções como trocar email e senha

**Comment by uira** [comment]
@leogermani Podia colocar também algumas infos: 
- ultimo acesso/atualização;
- espaço em disco usado;

Outra coisa é que é importante que fiquem registrados tantos os acessos/consultas, quanto as edições (isso já temos, né?)

**Comment by leogermani** [comment]
- [x] Fazer lista de admins e superadmins dos sites
- [x] Jogar fora página atual de "Papeis e usuários"
- [x] Fazer Agentes ficar sempre na busca, mesmo que este tipo de entidade esteja desabilitado
- [x] Na listagem de agentes, substituir label do botão para "Ver perfil"

**Comment by vnmedeiros** [comment]
validar a lista de admins e superadmins antes de remover a pagina "Papei e usuários"!

**Comment by marcus2703** [comment]
É possível paginar a aba "Atividades", além de possibilitar a ordenação por colunas.

**Comment by marcus2703** [comment]
Ao excluir espaço obtive erro SLIM.
![erro160.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56e08fcaba41d80e00c9ab16/125516c66e82c728ace21e0d46ed86882cd3d5f9cda5fd53b652fa912a5265296b51fa7d2481e52eea4679500c5e4eac415a0d16f8f9db78aea42062c80d55b98e30063e937f03a6aa8317b500bf23894a80b1ba8349c4ea3837aa.png)
