### ISSUE TITLE
Fazer esquema pra registrar namespaces de temas automaticamente e não precisar colocar no config

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#170]

**Comment by r-guimaraes** [comment]
semelhante aos plugins?

**Comment by leogermani** [comment]
não.

um esquema q vc não precise registrar tema nenhum no config. Que o Mapas varra as pastas, descubra os temas disponíveis e registre os namespaces automaticamente.

Ele faz isso acho que com os modulos

**Comment by vnmedeiros** [comment]
Observação: a tabela `public.subsite` utiliza o nome do namespace para identificar o tema utilizado.
