### ISSUE TITLE
Verificar se mensagens de denúncia e contatos estão sendo enviadas adequadamente

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#174]
. devem ir para os admins do subsite
. devem ir para os emails cadastrados na entidade que recebeu

**Comment by leogermani** [comment]
Enviar mensagens de contato também para o email do Agente dono da entidade

**Comment by marcus2703** [comment]
Não está enviando mensagem do tipo contato na plataforma.
Apenas recebi a cópia da mensagem, o endereço do destinatário e admin da plataforma não receberam nada.

Erro no envio de denuncia:
Address in mailbox given [to] does not comply with RFC 2822, 3.6.2.

**Comment by leogermani** [comment]
Vamos olhar esse erro @r-guimaraes . Qual foi a entidade para qual vc tava enviando o contato?

**Comment by marcus2703** [comment]
Atualizado em produção em 03/08/2018.

Testes realizados. Envio de contato funcionando, estando logado e deslogado na plataforma.

- Envio de denuncia com sucesso;
- Campos to e bcc corretos;
- Envio somente para destinatário correto;
![image](https://user-images.githubusercontent.com/12901157/43660651-07e40660-9736-11e8-87e2-4be61dafe5b7.png)
