### ISSUE TITLE
Fazer notificações de requisições irem por email para quem precisa responder

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#177]

**Comment by leogermani** [comment]
Falta link para as ações Aceitar ou Rejeitar

e/ou um link para o painel, onde vai poder aceitar ou recusar a requisição

**Comment by leogermani** [comment]
Verificar pq não aceitou o formato HTML, veja printscreen
![Captura de tela de 2018-07-09 15-17-06.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5385ea5febef97b1f959fde8/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2733dd5b465ef1b3b505a424fab5c585956e0ebc969f9ec6923ce4e01ffd4645970926b47a9ecd01eec00ba208b4dd7e4b88a1e93e02f39f5c9de116a415841c3aa1f27aa8b49ca52f74ee24c54a2133565ee77347c55d9.png)

**Comment by marcus2703** [comment]
É necessário verificar situação das entidades com situação de subsite_id NULL (dados migrados, anteriores ao SaaS e dados de Pontos de Cultura).

Entidades cujo o valor de subsite_id seja null gera erro na notificação, não gerando nem mesmo o envio da mesma para o painel de notificação.

A ação de rejeitar/aceitar deveria encaminhar e-mail também?

**Comment by marcus2703** [comment]
Atualização em produção realizada em 03/08/2018.
- Teste de notificação Requisição de mudança de propriedade: ok
![image](https://user-images.githubusercontent.com/12901157/43663860-4fd529a8-9741-11e8-92fd-f70def6e1c5e.png)

**Comment by marcus2703** [comment]
Não seria possível que a ação de aceitar/rejeitar a mudança de propriedade, assim como gerar a notificação na plataforma fosse encaminhada por e-mail?
![image](https://user-images.githubusercontent.com/12901157/43664131-2a2f1d84-9742-11e8-9fa7-c01842443254.png)
