### ISSUE TITLE
Substituir o campo de pesquisa do Mapa (GoogleMaps) por um campo de pesquisa de endereço (Metadado).

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#18]
![selecao_007](https://cloud.githubusercontent.com/assets/641411/17340459/96811c7e-58c6-11e6-8098-785fcdc0ee80.png)

**Comment by thaisrigolon** [comment]
@marylly @rafaelchavesfreitas @leogermani na verdade essa issue se tratava de removermos o vínculo do Mapas com o Google. Pelo que o @GustavoVS disse ainda existe um arquivo que chama a API do Google

![image](https://cloud.githubusercontent.com/assets/18294515/24768403/c77f3d86-1ad8-11e7-92e9-951afc56c6b4.png)

Podemos tirar esse arquivo que ainda carrega coisas da API do Google como default?

**Comment by avaloni** [comment]
Javascript da API do Google Maps retirado e busca por endereço corrigida, branch **RC** deste repositório.

**Comment by marcus2703** [comment]
Aparentemente está ok.
Testes realizados no ambiente http://mapas.dev.saas.mapas.cultura.gov.br não apresentam mais esses erros.
![image](https://cloud.githubusercontent.com/assets/12901157/25459253/d71a8238-2ab3-11e7-8575-c3f9b13cff69.png)
