### ISSUE TITLE
Configurar ID Cultura com ambiente de homologação

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#187]
ambiente de homologação do MediaLab

**Comment by marcus2703** [comment]
Já repassei o client id e secret ao Rodrigo para a URL de homologação da UFG.

**Comment by r-guimaraes** [comment]
Configurado e funcionando em http://mapas.medialab.ufg.br/

**Comment by marcus2703** [comment]
Validado.

Demais testes de SaaS podem ser feitos na estrutura MinC por já possuir servidos de ID Cultura configurados evitando assim criação de serviços de testes.

**Comment by marcus2703** [comment]
Podemos considerar essa issue concluida?

**Comment by leogermani** [comment]
sim
