### ISSUE TITLE
Separar infos geográficas na página da Entidade

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#189]
Separar as infos geográficas com um título, separando das demais informações de endereço

Informações geográficas (geradas automaticamente a partir da posição no mapa)

**Comment by marcus2703** [comment]
Agora é necessário clicar no item "Informações Geográficas" para exibir o detalhamento do mesmo.

![hmg_189.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56e08fcaba41d80e00c9ab16/125516c66e82c728ace21e0d46e0999d1cd3dbf0cda5fd53b652fa912a5265296b51fa7d2481e52eea4679500c5e4eac415a0d16f8f9db78aea42062c80d55b98e30063e937f03a6aa8317b500bf23894986bfb98f4ac0e93537aa.png)

**Comment by marcus2703** [comment]
Atualizado em produção em 31/07.
Separador funcionando.
![image](https://user-images.githubusercontent.com/12901157/43542809-7151f960-95a4-11e8-94dc-22c01909872c.png)
