### ISSUE TITLE
Mapas Como Serviço - SAAS

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#19]
Essa issue está relacionada ao **M**apas **A**s **A** **S**ervice. 

**Descrição:** 
O Mapas deve ter a possibilidade de em uma mesma instalação macro (no caso a instalação do MinC http://mapas.cultura.gov.br e/ou uma determinada instalação de um estado), utilizando um mesmo banco de dados, possa servir a várias plataformas diferentes, instanciadas por um determinado super administrador. O super administrador, através de um formulário no painel administrativo, deve ter acesso a configurações de um sub-site e delegar a um administrador o papel de edição dessa instância. Essas configurações devem contemplar: 
- url (sub-domínio)
- filtros
- cores
- logo
- zoom
- ponto central
- tema
- Administrador

**Referência:** 
- http://sniic.cultura.gov.br/sobre/mapas-culturais-apoio-para-estados-e-municipios/materiais-necessarios-para-personalizacao-do-mapa

**Issues Relacionadas:**
#20
#21

**Esboço:** 
![mapas_saas_03](https://cloud.githubusercontent.com/assets/641411/17904114/6656515c-6944-11e6-94f6-a0a2293d75ae.png)

**Comment by marylly** [comment]
- [x] Cores das entidades não está sendo configurada corretamente na instalação SaaS;
- [x] Criação do campo de Owner, agente responsável entidade do SaaS.

**Comment by GustavoVS** [comment]
[ ] - Trocar nome "Meus SaaS" por um nome mais intuitivo pro Usuário. Sugestão: "Meus Mapas"
[ ] - Incluir o item "Meus SaaS" (ou o novo nome que for colocado pra essa ĩdentificação) no Submenu do Usário quando ele está logado (está aparecendo apenas dentro do Painel)
[ ] - Corrigir Erro quando o Sub-Domínio não existe (ex:asdfasfa.devel.map.as)
[ ] - Dentro do Painel a opção de "Meus Agentes" está quebrada (Undefined variable: entity)
[ ] - Não tem uma opção para passar o "SaaS" para outro usuário. Mesmo ao passar o Owner, o novo Agente não tem acesso ao App "SaaS". Sugestões: 
    - A regra pra aparecer o SaaS deve ser se o Usuário for superAdmin ou  se o Usuário tiver algum SaaS
    - Habilitar Agentes Relacionados para a entidade "SaaS"

Necessário decisão:

[ ] - Falta definir como o usuário se torna Administrador apenas da instância do SaaS. Precisa ser definido, a sugestão inicial é: utilizar o plugin OriginSite ou criar um novo "OriginSaaS" (já que a url do mapa SaaS é mutável), onde o usuário que é dono ou tem acesso de edição do SaaS tem acesso as Entidades que tiverem sido criadas através desse SaaS.

**Comment by GustavoVS** [comment]
- [] - Trocar nome "Meus SaaS" por um nome mais intuitivo pro Usuário. Sugestão: "Meus Mapas"
- [] - Incluir o item "Meus SaaS" (ou o novo nome que for colocado pra essa ĩdentificação) no Submenu do Usário quando ele está logado (está aparecendo apenas dentro do Painel)
- [] - Corrigir Erro quando o Sub-Domínio não existe (ex:asdfasfa.devel.map.as)
- [] - Dentro do Painel a opção de "Meus Agentes" está quebrada (Undefined variable: entity)
- [] - Não tem uma opção para passar o "SaaS" para outro usuário. Mesmo ao passar o Owner, o novo Agente não tem acesso ao App "SaaS". Sugestões: 
    - A regra pra aparecer o SaaS deve ser se o Usuário for superAdmin ou  se o Usuário tiver algum SaaS
    - Habilitar Agentes Relacionados para a entidade "SaaS"

Necessário decisão:

- [] - Falta definir como o usuário se torna Administrador apenas da instância do SaaS. Precisa ser definido, a sugestão inicial é: utilizar o plugin OriginSite ou criar um novo "OriginSaaS" (já que a url do mapa SaaS é mutável), onde o usuário que é dono ou tem acesso de edição do SaaS tem acesso as Entidades que tiverem sido criadas através desse SaaS.

**Comment by GustavoVS** [comment]
- [x] - Trocar nome "Meus SaaS" por um nome mais intuitivo pro Usuário. Sugestão: "Meus Mapas"
- [x] - Incluir o item "Meus SaaS" (ou o novo nome que for colocado pra essa ĩdentificação) no Submenu do Usário quando ele está logado (está aparecendo apenas dentro do Painel)
- [x] - Corrigir Erro quando o Sub-Domínio não existe (ex:asdfasfa.devel.map.as)
- [x] - Dentro do Painel a opção de "Meus Agentes" está quebrada (Undefined variable: entity)
- [x] - Não tem uma opção para passar o "SaaS" para outro usuário. Mesmo ao passar o Owner, o novo Agente não tem acesso ao App "SaaS". Sugestões: 
  - A regra pra aparecer o SaaS deve ser se o Usuário for superAdmin ou  se o Usuário tiver algum SaaS
  - Habilitar Agentes Relacionados para a entidade "SaaS"

Necessário decisão:
- [x] - Falta definir como o usuário se torna Administrador apenas da instância do SaaS. Precisa ser definido, a sugestão inicial é: utilizar o plugin OriginSite ou criar um novo "OriginSaaS" (já que a url do mapa SaaS é mutável), onde o usuário que é dono ou tem acesso de edição do SaaS tem acesso as Entidades que tiverem sido criadas através desse SaaS.
- [x] Incluir os agentes relacionados a instalação do SaaS, e o agente relacionado terá acesso a todos os registros incluídos pela URL do registro do SaaS.
- [x] Bloquear a edição do campo slug;
- [x] Remover o campo no SaaS de instalação pai do registro do db_updates;
- [x] Na listagem de entidades  exibir a url ao qual foi cadastro o registro;
- [x] Incluir um campo para relacionar os selos que serão considerados como resultados verificados (selos oficiais);

**Comment by thaisrigolon** [comment]
- [x] O campo "Nome da instalação" precisa ser obrigatório e ter o ícone *
- [x] Alterar a nomenclatura de "Slug" para "Nome do domínio" e deixar cultura.gov.br como domínio fixo, exemplo: Nome do domínio: __________ .cultura.gov.br
- [x] **Na aba sobre:** Deletar campo de URL pai: Ex: http://mapas.cultura.gov.br
- [x] Alterar a nomenclatura "Sobre" para Página Inicial
- [x] Alterar a nomenclatura "Título:" para "Título da mensagem de boas-vindas"
- [x] Adicionar hífen no campo "Texto de boas-vindas"
- [x] Alterar descrição do item Texto de boas vindas para "Escreva um texto de boas-vindas de até 500 caracteres"
- [x] Quando o usuário clica para escrever o texto de boas-vindas, o título da janela que é aberta está errado. Corrigir para: Texto de boas-vindas
- [x] Na aba "Sobre" tem um campo que é Texto "sobre":
  O que significa esse campo? Onde ele aparece na página? Eu preenchi, mas não encontrei o texto na instalação.
- [x] **Na aba de entidades:** ter paleta de cores para selecionar as cores dos agentes, espaços, projetos, eventos e selos
- [x] **Logo da Instituição:** na hora que subimos a imagem parece que não subiu, mas quando entramos na página criada a imagem está aparecendo 
- [x] **Background:** a imagem sobe no painel, mas quando visualizamos a página inicial a imagem não aparece
- [x] **Na aba mapa:** Mostrar um mapa, não pedir latitude, longitude e zoons. Isso deve ser automático ao selecionar o ponto no mapa.
- [x] **Filtros na aba mapa:** Adicionar o filtro de município.

**Comment by marylly** [comment]
- [x] ~~Quando o filtro da linguagem for informado na instalação Saas, não exibir as mesmas opções no filtro da barra de busca do Mapas;~~ Na verdade isto não faz sentido.
- [x] Quando pesquisa por palavra chave no mapa usando os filtros das instalação SaaS, está dando erro 500 no retorno;

**Comment by thaisrigolon** [comment]
- [x] Usuário sem permissão ao subsite. Aparece a opção "meus subsites", mas ao clicar mostra uma tela em branco, conforme evidência:
  ![teste 1](https://cloud.githubusercontent.com/assets/18294515/19574247/315ab430-96e8-11e6-93e0-8aa9051b005d.png)
  ![teste 2](https://cloud.githubusercontent.com/assets/18294515/19574246/3155f012-96e8-11e6-8b74-16c098899d6d.png)
- [x] Não tem uma opção para passar o "SaaS" para outro usuário. Mesmo ao passar o Owner, o novo Agente não tem acesso ao App "SaaS".
- [x] Falta definir como o usuário se torna Administrador apenas da instância do SaaS. Precisa ser definido, a sugestão inicial é: utilizar o plugin OriginSite ou criar um novo "OriginSaaS" (já que a url do mapa SaaS é mutável), onde o usuário que é dono ou tem acesso de edição do SaaS tem acesso as Entidades que tiverem sido criadas através desse SaaS.
- [x] Incluir os agentes relacionados a instalação do SaaS e o agente relacionado terá acesso a todos os registros incluídos pela URL do registro do SaaS.
- [x] **Selos Verificadores:** O campo deve ser uma opção de busca trazendo os selos do usuário logado. Ele poderá selecionar os selos que pretende colocar como verificados.
- [x] **Filtro de linguagem:** Quando o filtro da linguagem for informado na instalação SaaS, deve ser exibido na busca das entidades as mesmas opções de filtro (exemplo: conforme imagem abaixo, deveriam aparecer apenas os filtros de Cinema e Cultura Indígena). No momento, o filtro é selecionado, mas todas as opções de linguagem continuam aparecendo.

![teste 1](https://cloud.githubusercontent.com/assets/18294515/19574563/adf50ddc-96e9-11e6-8539-c3b41e766618.png)
![teste 2](https://cloud.githubusercontent.com/assets/18294515/19574562/adf3d264-96e9-11e6-9f91-cde87759641c.png)

**Comment by marylly** [comment]
@rafaelchavesfreitas rola você atualizar o status desta issue, por gentileza?

**Comment by thaisrigolon** [comment]
**Mapa**
- [x] Adicionar o campo "Digite um endereço" no mapa:
  ![1](https://cloud.githubusercontent.com/assets/18294515/20393476/3815e628-acc3-11e6-90a8-410026fbacdf.png)
- [x] Aumentar a altura do mapa, pra ele ficar maior.
- [x] Deixar o zoom mínimo com padrão 18 e o zoom máximo com pradão 5. Tirar os campos "Zoom Mínimo" e "Zoom Máximo".

**Color Picker**
- [x] Após a seleção da cor, deve aparecer a cor selecionada e não o código:
  ![1](https://cloud.githubusercontent.com/assets/18294515/20393642/be2d7ac8-acc3-11e6-8d1e-445d0e1a8118.png)

Sugestão: 
![2](https://cloud.githubusercontent.com/assets/18294515/20393693/e6a48690-acc3-11e6-8727-20be3bf06f01.png)

**Comment by thaisrigolon** [comment]
> Deixar o zoom mínimo com padrão 18 e o zoom máximo com pradão 5. Tirar os campos "Zoom Mínimo" e "Zoom Máximo".

essa issue....

**Comment by rafaelchavesfreitas** [comment]
>  Não tem uma opção para passar o "SaaS" para outro usuário. Mesmo ao passar o Owner, o novo Agente não tem acesso ao App "SaaS".
 Falta definir como o usuário se torna Administrador apenas da instância do SaaS. Precisa ser definido, a sugestão inicial é: utilizar o plugin OriginSite ou criar um novo "OriginSaaS" (já que a url do mapa SaaS é mutável), onde o usuário que é dono ou tem acesso de edição do SaaS tem acesso as Entidades que tiverem sido criadas através desse SaaS.
 Incluir os agentes relacionados a instalação do SaaS e o agente relacionado terá acesso a todos os registros incluídos pela URL do registro do SaaS.

Existem agora os roles **saasSuperAdmin** e **saasAdmin** e estes usuários podem criar **admins** e **superAdmins** dos subsites da mesma maneira que um **superAdmin** criava **admins**

**Comment by rafaelchavesfreitas** [comment]
> Filtro de linguagem: Quando o filtro da linguagem for informado na instalação SaaS, deve ser exibido na busca das entidades as mesmas opções de filtro (exemplo: conforme imagem abaixo, deveriam aparecer apenas os filtros de Cinema e Cultura Indígena). No momento, o filtro é selecionado, mas todas as opções de linguagem continuam aparecendo.

as configurações de linguagem, tipo, etc são para filtrar as entidades da instalação principal que aparecerão no subsite, mas isto não significa que as linguagens, tipos, etc não devem aparecer como opção no cadastro. Um exemplo é um subsite que exibe só agentes e espaços da área de atuação _circo_ mas o usuário quer criar um espaço com as áreas de atuação _circo, teatro e dança_

**Comment by marylly** [comment]
- [x] #60 Página "Como Usar" - SaaS
- [x] #61 Imagens
- [x] #62 Markdown
- [x] #63 SaaS - Atribuição roles saasAdmin e saasSuperAdmin via agente
- [x] #66 Arrumar link do "Logo Instituição"
- [x] #67 Erro ao carregar 2 instâncias
- [x] #69 Entidades na cor config padrão
- [x] #70 Opção exibir agentes e espaços juntos não funciona
- [x] #71 HTML
- [x] #72 Botão Excluir
