### ISSUE TITLE
Verificar scrpits do último deploy

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#191]
carregar metadados geográficos

**Comment by leogermani** [comment]
Realmente não rodou um script em produção.

É preciso rodar:

load IBGE codes

**Comment by marcus2703** [comment]
Atualizado em produção em 31/07.
Dados carregados através de script de inserção dessas informações.

A atualização gerou duplicação da key geoSetor_censitario_cod em 3.976 registros da agent_meta.
A atualização gerou duplicação da key geoSetor_censitario_cod em 2.623 registros da space_meta.

Necessário avaliar correção.
