### ISSUE TITLE
Verificar bug do link do zip

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#192]

**Comment by marcus2703** [comment]
Homologado.
O link está apontando para o local correto.
![hmg_192.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56e08fcaba41d80e00c9ab16/125516c66e82c728ace21e0d46e0999d1cd3dafbcda5fd53b652fa912a5265296b51fa7d2481e52eea4679500c5e4eac415a0d16f8f9db78aea42062c80d55b98e30063e937f03a6aa8317b500bf23894981b6ba8d48c0e13437aa.png)

**Comment by marcus2703** [comment]
Atualizado em produção em 31/07.
Link para download dos arquivos funcionando.
