### ISSUE TITLE
Configurar cron para recriar pcache

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#193]

**Comment by nalomysouza** [comment]
Vocês estão fazendo como essa issue ? porque criamos um script e estamos executando no cron 
https://github.com/secultce/mapasculturais/commits/feature/cache-pending-adicionar-cron-job%23152

**Comment by vnmedeiros** [comment]
Para configurar o cron está disponível a seguinte URL:
`<server>/PermissionCache/recreate` que processa uma fila de tamanho igual a 100. 
ou `<server>/PermissionCache/recreate?size=5` para alterar o tamanho da fila de processamento.

**Comment by marcus2703** [comment]
Atualizado em produção em 31/07.
CRON configurado em ambiente de produção para ser executado a cada 60s..
