### ISSUE TITLE
Erro ao buscar endereços no Mapas

### ISSUE THREAD

**Issue by asaferamos** [culturagovbr/mapasculturais_descontinuado#202]
Busca utilizando a busca por endereço do Mapas apresenta problemas:
![image](https://user-images.githubusercontent.com/2385995/43276806-5dcd5b40-90dc-11e8-9fb1-63313eaef924.png)

Após realizar uma primeira busca por endereço e depois buscar utilizando a opção de desenhar um círculo, ocorre o erro: 
![image](https://user-images.githubusercontent.com/2385995/43277222-c4abe790-90dd-11e8-902a-a21a4a7cba82.png)

**Comment by marcus2703** [comment]
Homologado.
![hmg_202.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56e08fcaba41d80e00c9ab16/125516c66e82c728ace21e0d46e0999d1cd0d3fbcda5fd53b652fa912a5265296b51fa7d2481e52eea4679500c5e4eac415a0d16f8f9db78aea42062c80d55b98e30063e937f03a6aa8316b500bf23894986bfbe8e4dc1ea3437aa.png)

**Comment by marcus2703** [comment]
Atualizado em produção em 31/07.
Ao preencher endereço o mapa busca a localização a atualiza o mapa na tela.
