### ISSUE TITLE
Sugestões para o Painel de Gestão de Usuários do Mapa

### ISSUE THREAD

**Issue by Andreqlp** [culturagovbr/mapasculturais_descontinuado#204]
- [x] 1.Campo de busca
- [x] 2. Gerenciar administradores
- [x] 3. Botão de Ver Perfil
- [x] 4. Busca de eventos
- [x] 5. Páginas desconfiguradas
- [x] 6. Tabela de informações principais
- [x] 7. Tabela do log da atividades
- [x] 8. Opção de tornar rascunho?
- [x] 9. Link quebrado do ver info dos eventos
- [x] 10. Função de mesclar agentes

##  1.Campo de busca
![p05](https://user-images.githubusercontent.com/14170372/43329858-fcea6202-9197-11e8-9ccf-5c853ea4dd63.png)
- a caixa de texto não setá aceitando o espaço, tive que escrever o nome "dragao do mar" no bloco de notas e colar para dar certo.
- quando se clica no botão de buscar ele abre a caixa de seleção ao invés de fazer a ação de busca, a caixa se selão só deveria ser ativada ao clicar na  seta para baixo. 
- quando você seleciona uma opção ela não substitui o nome busca.

## 2. Gerenciar administradores
![p09 gerenciar administadores](https://user-images.githubusercontent.com/14170372/43330018-62c89b70-9198-11e8-9ebb-880e72bfabce.png)
- botão de "administradores" é muito perdido, acho que deveria vir abaixo da opção "gerenciar usuários", com um nome mais explicativo, tipo: Ver os administradores do sistema.

## 3. Botão de ver o perfil
![p01 - ux](https://user-images.githubusercontent.com/14170372/43330224-f92e2378-9198-11e8-907d-f6e40172ca79.png)
- poderia manter o perfil de usabilidade do mapas retirando o botão de "ver o perfil" e inserindo o link para o perfil no mode da própria entidade buscada. 

## 4. Busca de eventos
![p07 - lista muito longa](https://user-images.githubusercontent.com/14170372/43329919-1cbcd4b6-9198-11e8-90a3-37e516778360.png)
- eventos com várias ocorrências deixam a lista muito grande, uma sugestão seria mostrar a ocorrência mais próxima de acontecer ou a última que aconteceu e informar textualmente o total de ocorrências cadastradas.
- fiquei na dúvida se precisa mostrar a linguagem, classificação e tags.Isso fez quebrar o lugar onde aparecem os botões.

## 5. Páginas desconfiguradas
![erro](https://user-images.githubusercontent.com/14170372/43330327-33cdbae8-9199-11e8-91d4-c4620b280062.png)
- Relatório desconfigurado para oportunidades, projetos, eventos e espaços quando se clica no botão info. 
- Relatório desconfigurado para alguns agentes. Quando busquei pelo meu agente, o sistema me enviou >> http://minc.cultura.ce.gov.br/painel/userManagement//?userId=5016 , 
mas o meu id no mapas é o >> http://minc.cultura.ce.gov.br/agente/5352/ ; quando entro no http://minc.cultura.ce.gov.br/painel/userManagement//?userId=5352 ele me manda para otrua pessoa, cujo id real é >> http://minc.cultura.ce.gov.br/agente/5716/ uma loucuuura!

##  6. Tabela de informações principais
![p02 - tamanho das colunas](https://user-images.githubusercontent.com/14170372/43330609-10fbc856-919a-11e8-99db-ca52aee94537.png)
- rever o tamanho das colunas.
- retirar a marca ícone da entidade da coluna do id, pois já tem a informação no todo ta tabela.
- inserir o link no nome e não no id (padrão utilizado no mapa)
- faltam as abas de projetos e oportunidades

## 7. Tabela do log da atividades
![p03 - resumir e traduzir](https://user-images.githubusercontent.com/14170372/43330929-ee7542a2-919a-11e8-8cc7-ddd147d96609.png)
- na coluna descrição só vi as opções "Registro atualizado" e "Registro atualizado" que é a a mesma informação da coluna ação. Poderia unir as duas numa na coluna ação e informar sé é "atualizou" ou "criou". 
- retirar o .000000 da hora >> 2018-05-08 12:17:05.000000
- qual a diferença entre as colunas id e id da entidade? É preciso apontar isso no título da coluna.
- no tipo informar se é espaço, evento, agente, projeto ou oportunidade ao invés do endereço >> MapasCulturais\Entities\Agent

## 8. Opção de tornar rascunho?
![p04 - reitar a marca do evento](https://user-images.githubusercontent.com/14170372/43330961-ffcbb55e-919a-11e8-87fc-7d126ce045b4.png)
- não entendi pq aparece para o gerente a opção de tornar rascunho, já que o arquivar tem a mesma função.

## 9. Link quebrado do ver info dos eventos
O botão aponta para esse link: http://minc.cultura.ce.gov.br/painel/userManagement//?userId=

## 10. Função de mesclar agentes
https://github.com/culturagovbr/mapasculturais/issues/201

**Comment by vnmedeiros** [comment]
no item 5:

> Relatório desconfigurado para alguns agentes. Quando busquei pelo meu agente, o sistema me enviou >> http://minc.cultura.ce.gov.br/painel/userManagement//?userId=5016 ,
> mas o meu id no mapas é o >> http://minc.cultura.ce.gov.br/agente/5352/ ; quando entro no http://minc.cultura.ce.gov.br/painel/userManagement//?userId=5352 ele me manda para otrua pessoa, cujo id real é >> http://minc.cultura.ce.gov.br/agente/5716/ uma loucuuura!

O parâmetro `userId` recebe o ID do usuário do mapas (ID que identificar o usuário que realizou o cadastro no sistema), quando a URL `/agente/5352` é chamada esse ID passado é referente agente criado no mapas (informações diferentes id do agente é diferente do id do usuário do mapas)

**Comment by r-guimaraes** [comment]
O item 10 está em desenvolvimento aqui: https://github.com/culturagovbr/mapasculturais/issues/150

**Comment by r-guimaraes** [comment]
Sobre o item 8: Embora possuam semelhança conceitual, as ações "tornar rascunho" ou "arquivar" possuem efeitos diferente sobre a entidade.
