### ISSUE TITLE
Criar tema para pontos de memoria

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#207]
Tema filho novo para os pontos de memoria, mantendo pelo SAAS a configuração de entidades ativas, filtro padrão, etc.

Tirar filtros Área de atuação e Tipos (espaços)

Arrumar menu do topo, pq Pontos de Memória ocupa duas linhas (aumentar a largura)

Temática dos Pontos de Memoria
Acervo e centro de memória
Conhecimento e tradições orais
Povos e comunidades tradicionais
Culturas Afro-brasileiras
Culturas Indígenas
Culturas Populares
Cultura Cigana
Cultura LGBT
Cultura Digital
Cultura Estrangeira
Patrimônio Imaterial
Educação patrimonial
Turismo Comunitário
Pesquisa em Memória Social
Mídias Comunitárias
Arquivo/Arquivo Digital
Produção Cultural
Audiovisual
Artes visuais
Arte de rua
Rádio Comunitária
Televisão Comunitária
Economia Criativa
Artesanato
Circo
Dança
Música
Cinema
Fotografia
Teatro
Literatura

No formulário de inscrição, achamos essencial acrescentar dois campos de perguntas cujas respostas nos permitem averiguar o alcance de metas do PNSM.

Nesse caso, é importante colocar as legendas explicativas.  Sem elas, nem todos os usuários compreenderão as perguntas.

 

Já realizou o inventário participativo?

(  ) Sim    (  ) Não

 

* Inventário Participativo:  processo de inventariação do patrimônio material e imaterial em que os próprios grupos e comunidades locais atuam como protagonistas na identificação, seleção e registro das referências culturais mais significativas para suas memórias e histórias sociais.

 

Possui Conselho Gestor?

(   ) Sim      (   ) Não

 

**Conselho Gestor: instância deliberativa constituída por um grupo representativo da comunidade, responsável pelo acompanhamento das ações de museologia social desenvolvidas e pela interlocução com o estado e com os demais grupos e movimentos sociais, meios de comunicação locais e parceiros externos. Para sua formalização são realizados relatórios e atas com registro e informações sobre os membros e reuniões.

**Comment by uira** [comment]
@leogermani Que pena... tanta demanda pra atender usuarios e recurso de desenvolvimento sendo investido em burocracia... 🚮

**Comment by marcus2703** [comment]
- [x] corrigir a questão das cores das entidades (pegando cores padrão);
- [x] corrigir camadas de visualização do mapa (google e shapefiles), talvez seja apenas config do homolog;
- [x] inserir filtro de Município e UF;
- [x] inserir campo para informar/cadastrar os novos metadados de temática;

**Comment by marcus2703** [comment]
Em conversa com a área, eles pediram para adicionar os itens:  “Museologia Social” e “Memória Social” a listagem de área de atuação, isso é possível por tema? Ou está ligado ao core?
Outra colocação foi que a temática é múltipla escolha

**Comment by r-guimaraes** [comment]
Temática alterada pra múltipla escolha
