### ISSUE TITLE
Acesso a /busca/# sem nenhum parâmetro gera sobrecarga

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais_descontinuado#210]
É preciso tratar esse caso para que não retorne nada, ou 404, ou redirecione para alguma página válida

**Comment by leogermani** [comment]
essa solução foi revertida pq gerava outros problemas

**Comment by marcus2703** [comment]
Testado em homologação acesso a URL sem argumentos e redirecionamento funcionando sem travar a plataforma.
