### ISSUE TITLE
[Oportunidades-Avaliação] - Redistribuição de avaliação

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#216]
Alguns avaliadores podem apresentar impedimento para realizar a avaliação de algumas propostas, e neste caso, existe a necessidade da plataforma permitir que uma avaliação seja distribuída para outro avaliador.

**Comment by leogermani** [comment]
- [ ] ao avaliar uma inscrição, adicionar botão para avaliador informar que não pode fazer aquela avaliação. Isso é generico pra qualquer forma de avaliação. Dentro da tela de avaliação, tem esse botão e quando clica, abre um textarea para ele justificar.

- [ ] depois de fazer isso, essa inscrição some da lista dele

- [ ] Os donos da oportunidade recebem uma notificação avisando

- [ ] Na single da inscrição, vamos acrescentar uma área (aba ou lá em baixo), que mostra que são os avaliadores dessa inscrição. Essa lista é dividida em duas: Os avaliadores que estão na regra de distribuição e os que não estão na regra de distribuição

- [ ] Nessa lista, os que estão na regra de distribuição vem por padrão marcados como avaliadores. e os que não estão, não. O dono da oportunidade pode, então, des-selecionar e seleciontar avaliadores a partir dessa lista. Dessa maneira ele pode passar essa inscrição pra outro avaliador.

## no banco

- [ ] Adicionar 2 metadados às inscrições: um de avaliadores_excluidos e outro de avaliadores_incluidos para guardar as exceções as regras. Esses metadados guardam os ids dos avaliadores

## no código

- [ ] na função canUserEvalute (ou algo assim) adicionar essa verificação das exceções para retornar se o usuário pode ou não pode avaliar aquela inscrição.
