### ISSUE TITLE
[Oportunidades-Avaliação] - Não alterar número da inscrição (Proprietário Edital)

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#217]
Ao criar novas fases em uma oportunidade e importar as inscrições da fase anterior o sistema gera um novo número de inscrição. Embora exista a relação entre esses números, por questões de acompanhamento, é importante que o número permaneça sempre o original.
![image](https://user-images.githubusercontent.com/12901157/45902018-7a1c2900-bdbb-11e8-9777-3043c3d4e320.png)

**Comment by leogermani** [comment]
- [ ] Primeira etapa: Em todos os lugares, mostrar só o número da inscrição original, mas linkando normal para a url da inscrição da segunda ou terceira fase...

- [ ] Mudar tb a URL da inscrição das fases seguintes para usar sempre o id da primeira com o id da oportunidade

**Comment by marcus2703** [comment]
- Teste realizado e números da inscrição estão iguais em todas as fases.

![image](https://user-images.githubusercontent.com/12901157/46755074-8dbffe80-cc9a-11e8-9e33-4634d37d9db1.png)
