### ISSUE TITLE
[Oportunidades-Avaliação] Novo campo avaliação técnica

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#219]
Ao realizar a avaliação técnica, existe a necessidade de que o avaliador informe se a proposta apresenta exequibilidade ou não. Essa análise é feita juntamente com essa avaliação, sendo necessário um campo do tipo válido/inválido mesmo nesse tipo de avaliação.

Avaliamos o uso de 0/1 para esta situação, mas o mesmo alterava a média e não invalidava a proposta se fosse informado 0.

**Comment by leogermani** [comment]
Colocar opção para marcar avaliação como válida ou inválida

Na hora de calcular a média das notas, se algum avaliador tiver marcado como inválida, botar 0 pra média pra tudo

**Comment by marcus2703** [comment]
Em contato com a área que solicitou essa melhoria, foi dado o seguinte cenário.
- A avaliação deve receber nota independente do critério de inabilitação por exequibilidade;
- A inscrição será avaliada por 3 avaliadores, e para ser válida, deve ter 2 ou mais avaliações como válida;
- A media deve ser composta pelas 3 notas técnicas, independente se em uma delas ter sido considerada inexequível.

**Comment by marcus2703** [comment]
- [x] A media deve ser composta pelas 3 notas técnicas, independente se em uma delas ter sido considerada inexequível:
- [x] As inscrições 790645517 e 913405834 foram invalidades por 2 avaliadores e constam como validas no edital teste http://*/oportunidade/1073/#/tab=inscritos
[teste_avaliacao.xlsx](https://github.com/culturagovbr/mapasculturais/files/2461752/teste_avaliacao.xlsx)

**Comment by marcus2703** [comment]
- [x] O campo de exequibilidade está sendo validado, mas não impede de enviar a inscrição caso fique sem ser marcado.

**Comment by marcus2703** [comment]
- Refiz os testes de avaliação, e a plataforma está funcional quanto a questão da elaboração médias e da validação da exequibilidade. Desconsiderar apontamento anterior quanto a questão da composição da média e invalidação da inscrição.

**Comment by marcus2703** [comment]
- Resultado da verificação:
![image](https://user-images.githubusercontent.com/12901157/46767198-a5a77a80-ccba-11e8-8855-01d74b85d115.png)

**Comment by marcus2703** [comment]
- Teste de validação da obrigatoriedade de preenchimento do campo de exequibilidade.
![image](https://user-images.githubusercontent.com/12901157/46813378-f7004a00-cd4c-11e8-82ba-9891a391aae7.png)
