### ISSUE TITLE
Melhoria de performance do sistema

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#22]
Itens a serem considerados: 
- Cache
- Arquivamento de files
- Upload de arquivos
- Multiplos acessos

**Comment by nitaibezerra** [comment]
Sugiro considerarem o uso de indexadores como o elastic search. E, como
estratégia inicial fazer uso de índices no banco, e tabelas redundantes,
índices persistidos.

Em 23/08/2016 11:42 AM, "Robert Kapa" notifications@github.com escreveu:

**Comment by thaisrigolon** [comment]
Issue ok. Homologada pela La Fabbrica e MinC.
