### ISSUE TITLE
[Oportunidades-Avaliação] - Devolver avaliação para revisão/alteração

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#220]
Possibilitar ao proprietário da oportunidade a possibilidade de devolver uma avaliação já enviada para o Avaliador realizar a revisão/alteração da mesma.

Hoje, ao enviar a proposta o avaliador não tem mais como acessar a mesma.

**Comment by rafaelchavesfreitas** [comment]
a idéia é que as avaliações de todas as inscrições possam ser revisadas ou somente de inscrições específicas?

**Comment by marcus2703** [comment]
Apenas inscrições específicas inicialmente.

Mas há pedidos de revisão em relação a fase de recurso.

**Comment by marcus2703** [comment]
Testes realizados e foi possível:
- reabrir as avaliações para um avaliador;
- alterar avaliação já enviada;
- reenviar as avaliações;

**Tela do avaliador enviar as avaliações:**
![image](https://user-images.githubusercontent.com/12901157/50232414-04aefd00-0398-11e9-9301-2ccf56fd6bff.png)

**Tela após o avaliador enviar as avaliações:**
![image](https://user-images.githubusercontent.com/12901157/50232488-37f18c00-0398-11e9-99cf-a5bf871bdf65.png)
