### ISSUE TITLE
Obter informações de agente no evento pelo api

### ISSUE THREAD

**Issue by GabriAz** [culturagovbr/mapasculturais_descontinuado#225]
Boa tarde, precisamos consumir os seguintes conteúdos da api, porém não consegui localizar com exatidão os nomes corretos para adicionar ao jquery, poderiam me auxiliar ?

- Nome Agente (palestrante do evento)
- Foto do Agente (palestrante do evento)
- Descrição curta do agente (palestrante do evento)
- Tags associadas do evento

Neste caso, o Agente foi adionado a um "grupo de agentes" de nome Palestrantes. Segue exemplo:
http://mapas.cultura.gov.br/evento/3374/

**Comment by mateuswetah** [comment]
Yo Descobri!
Para as tags:
```
terms
```
Para o Palestrante:
```
user.{agents.{name,longDescription,shortDescription}}
```
Só não parece ter como separar de qual "grupo de agentes" ele veio, mas como neste caso estamos com um grupo só não tem problemas. Também não consegui aí pegar o Avatar dele, se alguém aí tiver um palpite antes de fecharmos a issue...

**Comment by marcus2703** [comment]
Já existe documentação sobre a utilização da API em http://docs.mapasculturais.org/mc_config_api/
Caso a dúvida persista, informações sobre uso da API deve ser solicitada através de canais de comunicação da comunidade de desenvolvimento: https://telegram.me/joinchat/AVzIFAqpz3VFIPehrPpbZQ
