### ISSUE TITLE
Endpoint findBySpace aparentemente não funciona.

### ISSUE THREAD

**Issue by mateuswetah** [culturagovbr/mapasculturais_descontinuado#226]
Galera estou apanhando novamente aqui com a API. Na instalação do MinC, eu faço a seguinte requisição:
`http://mapas.cultura.gov.br/api/event/findBySpace?spaceId=14748&@to=2018-09-12&@from2018-12-07`

E é retornado um array vazio. Mas se olharmos no Mapas, há eventos sim neste local, nestas datas:
http://mapas.cultura.gov.br/espaco/14748/#/tab=agenda

Estou deixando algum parâmetro de fora?

**Comment by leogermani** [comment]
tem uns errinhos na sua query. Falta o = depois do from e a data do from ta maior que a data do to.

Essa query aqui, por exemplo, funciona:

```
http://mapas.cultura.gov.br/api/event/findBySpace?spaceId=14748&@from=2018-11-22&@to=2018-11-22
```
