### ISSUE TITLE
No painel, ter uma visualização de todos as entidades que o usuário PODE editar aquela determinada entidade

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#23]
Atualmente a plataforma só mostra entidades criadas pelo próprio usuário, não as entidades legadas/cedidas por ele/para ele.  

![selecao_009](https://cloud.githubusercontent.com/assets/641411/17341277/33cbde76-58ca-11e6-90eb-8858c02741b2.png)

**Comment by marylly** [comment]
Disponibilizada aba de entidades liberadas ao qual o usuário recebeu permissão para editar.
Disponível no site: http://master.map.as/
@robertkapa @GustavoVS

**Comment by thaisrigolon** [comment]
- [x] Quando o usuário não criou nenhum espaço, mas foi "liberado" para ter acesso e editar um outro espaço não aparece o número no painel. Isso dificulta, pois o usuário pode pensar que não tem nenhum espaço cedido a ele. Deve ter um número no painel que indique os espaços que ele tem permissão.

![bug](https://cloud.githubusercontent.com/assets/18294515/19169571/7119f17e-8beb-11e6-8aee-7320a6f6f5d6.png)

![1](https://cloud.githubusercontent.com/assets/18294515/19169619/9f2b34b0-8beb-11e6-8b8a-fbc97addc886.png)

![2](https://cloud.githubusercontent.com/assets/18294515/19169666/dadae46a-8beb-11e6-8793-a0499ab0a0de.png)

@thaisrigolon acredito que devemos exibir de outra forma, porque realmente o espaço não é do usuário, apenas foi cedida a permissão de edição e controle.

@marylly qual seria a proposta de exibição?

Sugiro informar duas quantidades serem exibidas no painel, uma com a quantidade de entidades que o agente criou, e a outra quantidade ser das entidades com permissão concedidas, e para o usuário saber o que cada quantidade representa, ao passar o mouse sobre o número, vai exibir uma mensagem (tooltip) dizendo que são suas entidades ou entidades com permissão @thaisrigolon @GustavoVS @robertkapa

**Comment by thaisrigolon** [comment]
- [x] Alterar a nomenclatura "Liberado" para "Concedidos" (alterar nas outras entidades também)
- [x] Alterar a ordem das abas para: Ativos > Concedidos > Rascunhos > Lixeira (alterar nas outras entidades também)

![ordem](https://cloud.githubusercontent.com/assets/18294515/19169739/1da79888-8bec-11e6-8d7c-086b77fbb375.png)

**Comment by marylly** [comment]
@thaisrigolon @robertkapa @GustavoVS avaliar em http://master.map.as

**Comment by thaisrigolon** [comment]
@marylly, está ok. Só ficou pendente encontrar uma forma de exibição no painel quando o usuário tiver um espaço "concedido". Alguma sugestão?

**Comment by marylly** [comment]
Issue finalizada, por gentileza testar @thaisrigolon @GustavoVS @robertkapa

**Comment by thaisrigolon** [comment]
Ok, issue homologada.

**Comment by marylly** [comment]
PR aprovado, pode encerrar esse aqui? @thaisrigolon @GustavoVS @robertkapa

**Comment by thaisrigolon** [comment]
Sim, agora está ok.
