### ISSUE TITLE
Substituir o campo de cadastro (Latitude/Longitude) pelo campo de CEP.

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#25]
![selecao_008](https://cloud.githubusercontent.com/assets/641411/17340547/06300648-58c7-11e6-8ae4-e7dfe7e1c164.png)

**Comment by marylly** [comment]
Gente, não tenho entendimento completo dessa parte, mas isso já está rolando, correto? @GustavoVS @rafaelchavesfreitas

**Comment by rafaelchavesfreitas** [comment]
Também não entendi essa issue, pode explicar?

Em 30 de set de 2016 8:51 PM, "Marylly" notifications@github.com escreveu:

**Comment by marylly** [comment]
@robertkapa pode nos ajudar?

**Comment by GustavoVS** [comment]
No caso "Latitude/Longitude", é o momento em que o campo **Endereço** é preenchido por completo.
Essa issue é, em outras palavras, duplicada com a issue #11, referente a API de CEP.
