### ISSUE TITLE
Documentar API de escrita

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#27]

**Comment by avaloni** [comment]
Incluí no arquivo de documentação de API:

https://github.com/culturagovbr/mapasculturais/blob/rc/documentation/docs/mc_config_api.md

Era bom o @rafaelchavesfreitas dar uma olhada.

**Comment by diegodorgam** [comment]
Aguardando avaliação para fecharmos essa.

@rafaelchavesfreitas

**Comment by vitor-kato** [comment]
Acho que poderia colocar cada exemplo perto do seu método, mas de resto está OK
