### ISSUE TITLE
Armazenamento do histórico das alterações das informações: ter versionamento do histórico de alterações das entidades

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#29]

**Comment by robertkapa** [comment]
https://github.com/hacklabr/mapasculturais/issues/851

**Comment by marylly** [comment]
Funcionalidade disponibilizada para testes no servidor http://master.map.as.
Documentação disponível em: https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_user_history.md
@thaisrigolon @robertKapa @GustavoVS

**Comment by thaisrigolon** [comment]
O servidor http://master.map.as/ tá fora do ar?

**Comment by thaisrigolon** [comment]
@marylly:

- [x] Não é efetuado o armazenamento do histórico da entidade **Projetos**?

- [x] A apresentação do histórico não está boa. É preciso mostrar os 10 últimos registros e para ver os demais clicar num botão para expandir.

- [x] Em computadores com resolução de tela menor, não é possível ver todo o texto do registro:
![1](https://cloud.githubusercontent.com/assets/18294515/23025077/c00ea7aa-f443-11e6-989d-6e9bd3b68e68.png)

- [x] Ao clicar no botão salvar várias vezes, sem alterar nenhuma informação na entidade, é gerado um novo histórico a cada clique:
![bug](https://cloud.githubusercontent.com/assets/18294515/23024855/06990fa4-f443-11e6-85ce-52f149a66728.png)

**Comment by marylly** [comment]
>  Não é efetuado o armazenamento do histórico da entidade Projetos?

É realmente necessário registrar o histórico dos projetos? porque eles duram um espaço curto de tempo,  e não há mudanças expressivas como localização como acontece com espaços/agentes/eventos importantes na análise de informações. Além do mais, os projetos tem as inscrições e muitos campos, possuem muitas informações que geraria dados redundantes no banco de dados com histórico a cada alteração de forma desnecessária. @thaisrigolon @GustavoVS

**Comment by thaisrigolon** [comment]
> É realmente necessário registrar o histórico dos projetos? porque eles duram um espaço curto de tempo, e não há mudanças expressivas como localização como acontece com espaços/agentes/eventos importantes na análise de informações. Além do mais, os projetos tem as inscrições e muitos campos, possuem muitas informações que geraria dados redundantes no banco de dados com histórico a cada alteração de forma desnecessária.

Bom, o que vocês acham @GustavoVS @robertkapa @marcus2703 @donsalvatore?

**Comment by donsalvatore** [comment]
vamos lá

1 - projetos como guarda-chuva de eventos. O que define o tempo do projeto messe caso é a "coleção de eventos" que está abaixo desse guarda-chuva. Tanto é que em eventos você já pode fazer buscas por projetos. Ou seja, já possui temporalidade

2 - projetos como edital. Aqui o que poderia ajudar é um filtro do tempo em que as inscrições estavam abertas pois já se é obrigado a demarcar um lugar no tempo.

Acho que é isso.

Miguel Gondim de Castro
+55 11 971612502

**Comment by marylly** [comment]
@donsalvatore @thaisrigolon esse período de inscrição de um projeto/edital está na própria entidade, não seria necessário consultar um histórico, 
O maior problema que demandou o histórico era perda principalmente da localização, então se fosse alterado o espaço da localização 1 para a localização 2, eu não conseguia tirar um relatório sobre o espaço no período em que estava localização 1, exibindo na localização 2 indevidamente. Como o projeto está vinculado aos eventos e os agentes, não conseguimos ver a necessidade de registrar o histórico de pequenas modificações nas informações do projeto.

**Comment by donsalvatore** [comment]
Opa. Sobre o ponto 2 é justamente isso. O que quero dizer é outra coisa. Se quiserem fazer alguma melhora de filtros nos projetos seria responder a pergunta. Quais foram os formulários abertos no dia tal e ano tal. Não temos isso e por hora não vejo urgência mas é um pedido que já surgiu.

Outro ponto que sai do foco do mail mas está relacionado a tempo.

Mas um avanço mesmo e que sempre vejo mal usado é: ativar inscrições deveria ser um botão único e depois você configura horas dentro do formulário. O que tem de projeto com as datas marcadas p o povo pensa que é pra divulgar o período de um evento não tá escrito.

Hj em dia minha preocupação é com ajustes de interface e fluxo de carregamento dos dados (um caminho, ordem). Porque estamos indo ma direção de um belo banco de dados, super flexível mas zero ou quase zero de navegabilidade. É um labirinto. E c você coloca o iddacultura no meio então. Ixiii.

Mas enfim.


Miguel Gondim de Castro
+55 11 971612502

**Comment by marylly** [comment]
@thaisrigolon @GustavoVS correções disponíveis na _branch_ **rc**.

**Comment by vitor-kato** [comment]
@thaisrigolon @GustavoVS @marylly 

![selecao_003](https://cloud.githubusercontent.com/assets/21978887/23224508/7a448f04-f90d-11e6-8901-7ce468907001.png)
![selecao_004](https://cloud.githubusercontent.com/assets/21978887/23224509/7a45457a-f90d-11e6-8129-635c49f61441.png)
![selecao_005](https://cloud.githubusercontent.com/assets/21978887/23224510/7a48469e-f90d-11e6-9b0f-fc420cfc1c06.png)
![selecao_006](https://cloud.githubusercontent.com/assets/21978887/23224511/7a57c646-f90d-11e6-8e1d-f032db7c27c5.png)

- [x] Histórico não cria novos itens quando clica varias vezes no botão salvar, porém:   
     - [x]  Aviso de "Edições salvas" ainda aparece diversas vezes quando Salvar é clicado e também quando não foi feita nenhuma edição.


- [x] Edições estão contidas dentro de uma lista com 5 opções inicialmente visíveis

- [x] Lista é responsiva e apresenta todas informações para o usuário com telas menores

**Comment by marylly** [comment]
>  Aviso de "Edições salvas" ainda aparece diversas vezes quando Salvar é clicado e também quando não foi feita nenhuma edição.

É um comportamento normal, porque é feita uma solicitação de armazenamento, se a cada clique efetuar uma edição, a info será gravada e a mensagem exibida.
@vitor-kato

**Comment by vitor-kato** [comment]
Mas e quando o usuário não fizer nenhuma alteração e clicar para salvar? Não haveria a necessidade dessa mensagem como está agora agora. Algo do tipo "Nenhuma alteração feita" seria melhor. Seria mais claro para o usuário que ele não fez nenhuma alteração. 

No momento se há intenção de se fazer alguma alteração, mas por algum "deslize" da pessoa que a estiver fazendo, nada for mudado. A pessoa vai achar que mudou o que ela queria e não vai perceber que na realidade nada foi mudado.

Com uma mensagem "Nenhuma alteração feita" o usuário vai perceber melhor seu erro.
@marylly

**Comment by marylly** [comment]
@thaisrigolon @GustavoVS @vitor-kato podemos abrir uma issue referente a este ponto, mas não tem relação com a funcionalidade do histórico de entidades da plataforma, ok?

**Comment by thaisrigolon** [comment]
Ok. Issue homologada.
