### ISSUE TITLE
Criar opção de limite numério de inscrições em projetos

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#30]
Na entidade projetos existe a opção "Inscrições". Essa opção possui uma limitação de número de inscrições por usuário (por agente) e por data (data de inicio e fim). No entanto não há limite numérico de vagas. Precisa ser criada uma opção que limite a um determinado número de vagas. 

EX.:

Como funciona hoje:
**Evento - Oficina de teatro**
**Data de inicio:** 01/01/2016
**Data de fim:** 15/01/2016

Quando terminam as incrições? R: apenas no dia 15/01/2016. Não há limite automático de vagas. 

Como deveria operar: 
**Evento - Oficina de teatro**
**Data de inicio:** 01/01/2016
**Data de fim:** 15/01/2016
**Vagas:** 30

Quando terminam as incrições? R: No dia 15/01/2016 ou quando completarem 30 vagas. Nesse caso, se completarem 30 inscrições e ainda estiver dentro do tempo vigente, o sistema deve mostrar um modal ou desabilitar as inscrições.

**Comment by robertkapa** [comment]
https://github.com/hacklabr/mapasculturais/issues/884

**Comment by marylly** [comment]
- [x] Apesar  do limite de inscritos informada, é permitido enviar a inscrição e aprovar.

**Comment by thaisrigolon** [comment]
Não conseguimos editar o número máximo de vagas, conforme evidência:

![1](https://cloud.githubusercontent.com/assets/18294515/19778443/8cffd7e8-9c5b-11e6-90b1-24082a96730c.png)

**Comment by marylly** [comment]
@thaisrigolon o número de vagas é calculada de acordo com o número máxmo de inscrições, não pode  ser editada mesmo.
O que tem que acontecer é não deixar as inscrições acontecerem caso atinja o limite de Número Máximo de Inscrições, o que já existia mas não bloqueava.

**Comment by thaisrigolon** [comment]
Uma dúvida: o número máximo de inscrições é o limite de vagas ou é o número máximo de envios por agente responsável? Há essa ambiguidade, pois quando clicamos para inserir o número máximo de inscrições aparece a tela com descrição de número máximo de inscrições por agente. Está confuso, poderia esclarecer, por favor?

![1](https://cloud.githubusercontent.com/assets/18294515/19805721/dadf536e-9cf4-11e6-8a3b-ff38bbd8d30d.png)

**Comment by marylly** [comment]
Corrigida a funcionalidade e nomenclatura dos campos de limitação de inscrições num projeto.
Poderiam verificar @thaisrigolon  @GustavoVS @robertkapa

Funcionalidade disponível na branch master.

**Comment by thaisrigolon** [comment]
Estou tentando criar um novo usuário pra testar a inscrição, mas gera o seguinte erro no master:

![1](https://cloud.githubusercontent.com/assets/18294515/20538721/838b25d6-b0d9-11e6-83e9-dbd4449f1913.png)

**Comment by marylly** [comment]
@thaisrigolon problema corrigido.

**Comment by thaisrigolon** [comment]
@marylly o erro ainda persiste... não consigo criar novo usuário para testar.

**Comment by marylly** [comment]
Acabei de criar um usuário eu funcionou normalmente @thaisrigolon.

**Comment by thaisrigolon** [comment]
Eu vi, mas aqui não estamos conseguindo. Tentei em mais de um computador. Vou utilizar o seu usuário pra testar.

**Comment by thaisrigolon** [comment]
Quando criei o projeto coloquei as vagas com no máximo 2, mas foi possível fazer mais, conforme evidência:

![1](https://cloud.githubusercontent.com/assets/18294515/20564194/3cb193b2-b173-11e6-8f32-ea1fa008c9f7.png)

![2](https://cloud.githubusercontent.com/assets/18294515/20564197/409ddfe4-b173-11e6-9acc-91778bb4a727.png)

**Comment by marylly** [comment]
@thaisrigolon por gentileza, poderia testar novamente?

**Comment by thaisrigolon** [comment]
- [x] Quando apareceu que não havia mais vagas disponíveis, a linha ficou desconfigurada na página, conforme evidência:
![2](https://cloud.githubusercontent.com/assets/18294515/20606653/8dde6418-b259-11e6-8227-bbfddcf22be1.png)

- [x] Precisa ter um aviso para o agente que criou o edital de que as inscrições se esgotaram, pois já chegou no limite de vagas. Poderia ser uma mensagem ao lado das inscrições enviadas. 
Por exemplo: 2 inscrições enviadas. | Número máximo de vagas no projeto: 2 
Pode ser em outro lugar, mas essa informação precisa ter.
![3](https://cloud.githubusercontent.com/assets/18294515/20606674/b34af4b4-b259-11e6-909b-f27ada1022cc.png)

- [x] A aba de notificação fica aparecendo na parte superior ao salvar... e depois some.
![1](https://cloud.githubusercontent.com/assets/18294515/20606710/e3d8c502-b259-11e6-88ba-2bc7b39006e2.png)

**Comment by marylly** [comment]
" Quando apareceu que não havia mais vagas disponíveis, a linha ficou desconfigurada na página, conforme evidência." Não consegui simular esta situação @thaisrigolon

**Comment by marylly** [comment]
"A aba de notificação fica aparecendo na parte superior ao salvar... e depois some." Esse aqui também não consegui simular, testei os dois itens do master, e não consegui fazer acontecer, se puder demonstrar para mim, eu agradeço @thaisrigolon.

**Comment by thaisrigolon** [comment]
Evidência da aba de notificação que fica aparecendo na parte superior ao lado da aba projetos: Aparece bem rápido e depois some, mas não deve aparecer. No vídeo, é possível ver em dois momentos. 1) Depois de apertar "ok" na Fake Authentication e 2) Depois quando cliquei para ir na página do evento "Festa Africana": http://pt-br.tinypic.com/r/108bi4w/9

**Comment by thaisrigolon** [comment]
- [ ] Quando as inscrições estiverem esgotadas, deve aparecer uma mensagem para o agente que tenta fazer a inscrição:

![1](https://cloud.githubusercontent.com/assets/18294515/20670399/df123478-b55f-11e6-9378-549df99a29ab.png)

**Comment by marylly** [comment]
> Evidência da aba de notificação que fica aparecendo na parte superior ao lado da aba projetos: Aparece bem rápido e depois some, mas não deve aparecer. No vídeo, é possível ver em dois momentos. 1) Depois de apertar "ok" na Fake Authentication e 2) Depois quando cliquei para ir na página do evento "Festa Africana": http://pt-br.tinypic.com/r/108bi4w/9

@thaisrigolon isso acontece porque está carregando os componentes da tela, não é um erro.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
