### ISSUE TITLE
Controle de atualização das informações 2

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#31]
O sistema deve calcular quanto tempo um determinado cadastro das entidades agente e espaço foi criado. Se Espaço e/ou agente tiverem sido criados há mais de 4 meses e não houver qualquer tipo de atualização, o sistema deve mandar um EMAIL para o agente, sugerindo que o cadastro seja atualizado.

**Comment by marylly** [comment]
Verificar a funcionalidade de envio de e-mail na branch https://github.com/hacklabr/mapasculturais/tree/devel-mailer
- [x] Criar documentação referente a configuração do envio de e-mail pelo Mapas;
- [x] Criar arquivo que será executado via bash/cron;
- [x] Criar documentação referente a configuração da execução do envio de e-mails via cron.

**Comment by marylly** [comment]
Documentação disponível em: https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_config_plugins.md#mailer
Poderiam testar @thaisrigolon @robertkapa @GustavoVS
Funcionalidade disponibilizada na branch master.

**Comment by thaisrigolon** [comment]
@marylly, por favor, colocar no master para testarmos?

**Comment by marylly** [comment]
Já está disponível nesta branch @thaisrigolon!

**Comment by GustavoVS** [comment]
@marylly não consegui testar.
o arquivo 'notifications.sh' está dando erro:

```
./notifications.sh: line 25: 19400 Killed                  MAPASCULTURAIS_CONFIG_FILE=$CONFIG HTTP_HOST=$DOMAIN REQUEST_METHOD='CLI' REMOTE_ADDR='127.0.0.1' REQUEST_URI='/' SERVER_NAME=127.0.0.1 SERVER_PORT="8000" php ../src/protected/send-notifications.php $SAVE_LOG
```

**Comment by GustavoVS** [comment]
@marylly consegui executar mas só funciona se executar o script como root. Precisa funcionar ao executar com o usuário da aplicação.

**Comment by marylly** [comment]
mas acontece o mesmo erro de não ter permissão de escrever na pasta o log
de execução? @GustavoVS

**Comment by GustavoVS** [comment]
Já está funcionando corretamente com o usuário da aplicação.
