### ISSUE TITLE
Controle de atualização das informações 1

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#32]
O sistema deve avisar de forma automatica e peridodicamente todos os cadastros “velhos” para se atualizarem. Como a issue deve operar? O sistema deve calcular quanto tempo um determinado cadastro das entidades agente e espaço foi criado. Se Espaço e/ou agente tiverem sido criados há mais de 4 meses e não houver qualquer tipo de atualização, o sistema deve avisar, quando o usuário se logar, por meio do painel de notifications, que o usuário deve manter seu cadastro atualizado.

**Comment by robertkapa** [comment]
https://github.com/culturagovbr/mapasculturais/issues/32

**Comment by marylly** [comment]
Documentação sobre a funcionalidade: https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_config_plugins.md#notificações

**Comment by marylly** [comment]
Foi incluída a funcionalidade de arquivar e desarquivar entidades para evitar que o usuário fique recebendo notificações de registros desatualizados de entidades que estão obsoletas ou que não estão sendo mais utilizadas.

**Comment by GustavoVS** [comment]
- [x] A Notificação aparece apenas com um botão Ok, deve aparecer um Botão para ir Editar a Entidade.
- [x] Quando uma instalação do Mapas atualiza a aplicação com a criação do campo **update_timestamp** buscar a data do último login do usuário responsável pela entidade e colocar no campo **update_timestamp** da entidade.

**Comment by marylly** [comment]
Em qual momento vai atualizar o campo update_timestamp com a hora atual da instalação quando atualiza a aplicação e gera as notificações que é necessário atualizar a entidade? Se eu não me engano, se não tem nada no update_timestamp, utiliza o campo create_timestamp. @GustavoVS.

**Comment by marylly** [comment]
@GustavoVS @thaisrigolon @robertkapa, testar, por gentileza.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
