### ISSUE TITLE
Quando um novo agente é inserido, ao clicar em publicar o sistema permanece no modo de edição. Correção: o status deve ser de publicado e não de edição

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#35]
A tela continua em modo de edição

![screencapture-sp-master-map-as-agentes-edita-6-1470844321564](https://cloud.githubusercontent.com/assets/641411/17560670/4d57c0fa-5ef9-11e6-85c0-8de5c35dd9d9.png)

**Comment by marylly** [comment]
@thaisrigolon @GustavoVS poderiam verificar, por gentileza? Se encontra na _branch_ rc.

**Comment by GustavoVS** [comment]
@marylly está dando erro ao atualizar para o branch RC:

![selecao_019](https://cloud.githubusercontent.com/assets/7750643/23622222/99ba0828-027c-11e7-9fce-8df36827a16c.png)

Antes do erro na página, também aparecem esses erros no deploy.sh (PHP Fatal error:  Call to a member function getRevisionData() on a non-object in /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntityRevision.php on line 137):

![selecao_020](https://cloud.githubusercontent.com/assets/7750643/23622273/c4ee7e2a-027c-11e7-8332-db9c711dd7de.png)

**Comment by GustavoVS** [comment]
@marylly efetuei o teste, está OK.
Quando puder coloca no branch v3 e pra lançarmos numa próxima tag
