### ISSUE TITLE
Melhorar usabilidade de relação entre agentes - dentro da entidade, ver os agentes que tem controle sobre a mesma

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#36]
- [x] Criar um grupo de adminstradores da entidade no single de cada entidade, onde é permitido remover agentes ou conceder a entidade que está sendo exibida;
- [x] Criar um menu de permissões onde exibe os usuários que eu cedi permissão de edição de alguma entidade que eu sou proprietária;
- [x] Na home do panel de cada entidade, incluir uma aba com as entidades que cederam permissão de edição ao usuário logado;

**Comment by marylly** [comment]
Disponibilizado para teste no link: http://master.map.as

**Comment by marylly** [comment]
Poderiam testar @thaisrigolon @GustavoVS @robertkap, por gentileza ?

**Comment by thaisrigolon** [comment]
- [x] Quando o usuário tem um agente cedido e clica para visualizar esse agente, a tela que abre é na página de agentes ativos. Deveria abrir na página dos agentes cedidos:

![teste 1](https://cloud.githubusercontent.com/assets/18294515/19573951/04d22048-96e7-11e6-96b7-fa4f48f006c6.png)
![teste 2](https://cloud.githubusercontent.com/assets/18294515/19573950/04c2eed4-96e7-11e6-8293-10c1e9b870ca.png)

**Comment by GustavoVS** [comment]
"Quando o usuário tem um agente cedido e clica para visualizar esse agente, a tela que abre é na página de agentes ativos. Deveria abrir na página dos agentes cedidos:" 

https://github.com/hacklabr/mapasculturais/pull/964

**Comment by marylly** [comment]
PR já aprovado, já está ok? @GustavoVS @robertkapa @thaisrigolon

**Comment by thaisrigolon** [comment]
Sim, está ok.
