### ISSUE TITLE
no tema culturaviva, adicionar filtro para buscar apenas eventos com relacao a pontos de cultura.

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#39]
Atualmente, no cultura viva http://culturaviva.gov.br/busca/##(global:(enabled:(event:!t),filterEntity:event)) o ambiente esta mostrando todos os eventos cadastrados do sniic. 

![selecao_018](https://cloud.githubusercontent.com/assets/641411/18179706/258e8a50-705a-11e6-896b-ababa6ad1eba.png)

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
