### ISSUE TITLE
Integrar melhor mapas.cultura.gov.br com culturaviva.gov.br

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#40]
mudar about do culturaviva.gov.br, explicar atraves de alguns links a relação entre as duas plataformas

**Comment by thaisrigolon** [comment]
- [x] Atualizar a página **Sobre** das Bibliotecas (http://bibliotecas.cultura.gov.br/sobre/)

Texto validado:

# Sobre o Mapa das Bibliotecas
O Mapa das Bibliotecas é uma das peças do Cadastro Nacional de Bibliotecas e está voltado para a difusão e promoção das bibliotecas brasileiras, a fim de reunir informações sobre todos os tipos de bibliotecas, especialmente, as públicas e comunitárias.

Os dados estão integrados com o [Mapa da Cultura](http://mapas.cultura.gov.br/), sendo assim, todas as bibliotecas cadastradas no Mapa das Bibliotecas ou no Mapa da Cultura aparecem nas duas instalações, em tempo real.

A plataforma foi desenvolvida pelo Instituto TIM em parceria com o Ministério da Cultura. Você encontra mais informações sobre a ferramenta Mapas Culturais no site do [Instituto TIM](https://institutotim.org.br/project/mapas-culturais/).

**Realização**
Inserir a Marca do Instituto TIM, a marca do MinC e a marca do SNBP


- - - 


- [x] Inserir página **Sobre** no SNIIC (http://mapas.cultura.gov.br/)

Texto validado:

# Sobre o Mapa da Cultura
O Mapa da Cultura é um espaço para integrar e dar visibilidade para projetos, artistas, espaços, eventos culturais e seus produtores. Ele é a principal base de informações e indicadores do Ministério da Cultura, agregando cadastros de diferentes programas e ações.

A instalação agrega os dados do [Museus BR](http://museus.cultura.gov.br/), [Mapa das Bibliotecas](http://bibliotecas.cultura.gov.br) e [Rede Cultura Viva](http://culturaviva.gov.br/), que possuem plataformas próprias, mas que tem as informações integradas pelo [Mapa da Cultura](http://mapas.cultura.gov.br/).

A plataforma foi desenvolvida pelo Instituto TIM em parceria com o Ministério da Cultura e a partir de outubro de 2015 foi adotado pelo Sistema Nacional de Informações e Indicadores Culturais (SNIIC). 

Você encontra mais informações sobre a ferramenta Mapas Culturais no site do [Instituto TIM](https://institutotim.org.br/project/mapas-culturais/).

**Realização**
Marca do Instituto TIM e marca do MinC

- - - 

- [x] Inserir página **Sobre** no MuseusBR (http://museus.cultura.gov.br/)

Texto validado:

# Sobre o Museusbr

A prefeitura de São Paulo e o Instituto TIM se uniram em 2013 em um esforço conjunto para dar mais qualidade à gestão cultural dos municípios e estados. O objetivo era reunir informações sobre agentes, espaços, eventos e projetos culturais por meio de uma ferramenta colaborativa, fornecendo ao poder público uma radiografia da área de cultura e ao cidadão um mapa de espaços e eventos culturais da cidade. Dessa parceria surgiu Mapas Culturais, um software livre que pode ser adotado gratuitamente por qualquer cidade ou estado, e que no Ibram, leva o nome Museusbr.

As bases para o desenvolvimento do projeto foram lançadas no Encontro Mapas Culturais, em julho de 2013, que reuniu agentes culturais de vários países da América Latina, do Ministério da Cultura e da prefeitura de São Paulo para discutir a criação de uma ferramenta de mapeamento de iniciativas culturais, gestão cultural e geração de indicadores.

A plataforma está alinhada ao Sistema Nacional de Informação e Indicadores Culturais do Ministério da Cultura (SNIIC) e contribui para que os gestores públicos realizem alguns dos objetivos do Plano Nacional de Cultura. A instalação Museusbr foi implementada no final de 2015 substituindo a plataforma do Cadastro Nacional de Museus trazendo novas funcionalidades e serviços aos usuários e pesquisadores da área dos museus. Georreferenciamento, buscas avançadas, cruzamento de dados e disponibilização dos dados em formato de planilha são alguns dos benefícios que fizeram o Ibram optar pelar utilização do software Mapas Culturais, que trouxe maior qualificação da informação para a área dos museus no país.

Mais informações sobre a ferramenta Mapas Culturais no site do [Instituto TIM](https://institutotim.org.br/project/mapas-culturais/).

Para contato sobre dúvidas, sugestões, por favor, utilize o endereço cnm@museus.gov.br

**Realização**
Marca do Instituto TIM e marca do Museusbr

**Comment by thaisrigolon** [comment]
- [x] Texto validado:

# Sobre a Rede Cultura Viva
A Rede Cultura Viva é o conjunto de Pontos e Pontões de Cultura, organizações governamentais e não governamentais, lideranças, gestores, coletivos, grupos, povos e comunidades tradicionais, iniciativas urbanas e rurais, movimentos artísticos, culturais e socioeducativo, coletivos e redes, que atuam pela promoção e fortalecimento da cultura.

A Plataforma Rede Cultura Viva é a ferramenta de implementação do Cadastro Nacional de Pontos e Pontões de Cultura, instrumento da Política Nacional de Cultura Viva, instituída pela Lei nº 13.018/2014 e regulamentada pela Instrução Normativa MinC nº 08 de 11 de maio de 2016. A gestão da Plataforma é realizada por meio de Comissão de Gestão Compartilhada com composição paritária entre administração pública e sociedade civil.

Os dados estão integrados com o [Mapa da Cultura](http://mapas.cultura.gov.br/), sendo assim, todos os Pontos e Pontões de Cultura cadastrados na Rede Cultura Viva ou no Mapa da Cultura aparecem nas duas instalações, em tempo real.

A plataforma foi desenvolvida pelo Ministério da Cultura com apoio do Hacklab e em parceria do Instituto TIM. Você encontra mais informações sobre a ferramenta Mapas Culturais no site do [Instituto TIM](https://institutotim.org.br/project/mapas-culturais/).

**Realização**
Marca do Instituto TIM, marca do MinC e marca Cultura Viva

**Comment by thaisrigolon** [comment]
@marcus2703 precisamos de um retorno sobre o texto da página **Sobre** do Cultura Viva. É o único pendente.

**Comment by diegodorgam** [comment]
Fechamos esse já correto @marcus2703 ?

**Comment by marcus2703** [comment]
Os textos não estão em produção ainda.
Mas são esses mesmos.

**Comment by thaisrigolon** [comment]
@marcus2703 está pendente apenas o **Sobre** da instalação Rede Cultura Viva, mas precisa atualizar o tema Rede Cultura Viva e fazer com que a url http://culturaviva.gov.br/sobre pare de redirecionar para http://culturaviva.gov.br/sobre-a-lei-cultura-viva/

**Comment by thaisrigolon** [comment]
@marcus2703 estamos aguardando o redirecionamento da url http://culturaviva.gov.br/sobre para http://culturaviva.gov.br/sobre-a-lei-cultura-viva/. Tem alguma previsão?

**Comment by thaisrigolon** [comment]
Como no tema da Rede Cultura Viva a página "sobre" é diferente das demais, vamos manter como está atualmente e fechar esta issue.
