### ISSUE TITLE
No tema de bibliotecas, inserir a possibilidade de anexar arquivos .pdf em determinados campos

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#42]

**Comment by thaisrigolon** [comment]
@marcus2703, podemos fechar essa issue?

**Comment by marcus2703** [comment]
A DLLLB não manifestou quais campos desejaria colocar para envio de arquivos.
A nova coordenação ainda está se apropriando da ferramenta. Assim podemo encerrar essa demanda, e caso necessário abrir uma específica para atendimento da coordenação atual.
