### ISSUE TITLE
Melhoria de usabilidade nas entidades - breadcrumb

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#48]
Inserir breadcrumb nas entidades

![graceful-breadcrumb-preview](https://cloud.githubusercontent.com/assets/641411/18182908/48ba3aca-7068-11e6-9d9e-12a8a8b52059.jpg)

**Comment by marylly** [comment]
[ ] O link do painel quando estou no Agentes não funciona;
[ ] Incluir o bread crumb no single do Agente;

O breadcrumb deve ser incluído no fluxo das entidades:
[ ] Projetos;
[ ] Eventos;
[ ] Selos;
[ ] SaaS.

**Comment by marylly** [comment]
- [x] O link do painel quando estou no Agentes não funciona;
- [x] Incluir o bread crumb no single do Agente;

O breadcrumb deve ser incluído no fluxo das entidades:
- [x] Projetos;
- [x] Eventos;
- [x] Selos;
- [x] SaaS;
- [x] Espaços.
- [ ] Testar nos temas existentes do Mapas.

**Comment by marylly** [comment]
Disponibilizado na branch devel-SaaS, mas ainda tenho dúvida do local onde vai ficar. Poderiam dar uma olhada @robertkapa @GustavoVS @thaisrigolon

**Comment by thaisrigolon** [comment]
@marylly, o local que deve ficar é no topo abaixo do menu.

Não conseguimos testar agora porque o ambiente está quebrado (http://devel.map.as/).

**Comment by thaisrigolon** [comment]
- [x] No momento, o breadcrumb está na parte inferior da página. Deve ficar no topo, conforme a indicação:

![breadcrumb](https://cloud.githubusercontent.com/assets/18294515/19781781/c4187844-9c69-11e6-86a4-417f34f8d035.png)
- [x] O breadcrumb deve seguir esse padrão, com a identidade visual do mapas:
  ![6](https://cloud.githubusercontent.com/assets/18294515/19782040/cfbcb66e-9c6a-11e6-8306-b6acff46e197.png)
  ![7](https://cloud.githubusercontent.com/assets/18294515/19782053/e215f1b8-9c6a-11e6-8399-f80ec46a7136.png)

**Comment by marylly** [comment]
Por gentileza, verificar @thaisrigolon @GustavoVS @robertkapa

**Comment by thaisrigolon** [comment]
- [x] Alterar a cor da barra porque o cinza está deixando o breadcrumb bem apagado... 
![1](https://cloud.githubusercontent.com/assets/18294515/20352014/b96bf02c-abfc-11e6-8d09-1b38acc58cc9.png)

- [x] Alinhar o breadcrumb a partir da parte de edição das informações, conforme indicado abaixo:
![2](https://cloud.githubusercontent.com/assets/18294515/20352248/b926ae62-abfd-11e6-9507-9417ddc4cc44.png)

- No breadcrumb deve ter o histórico conforme abaixo:
Exemplo: Clico na página de um agente, o breadcrumb deve ficar assim:
**Painel > Meus Agentes > Agente** (sendo que a página que eu estou deve ficar marcada, indicando que é a página atual. As páginas anteriores devem ser clicáveis)

**Comment by marylly** [comment]
@thaisrigolon poderia homologar por gentileza?

**Comment by thaisrigolon** [comment]
Testado no ambiente master. Só ficou faltando o seguinte:

- [x] A página que o usuário está deve ficar destacada no breadcrumb, indicando que é a página atual. Essa aba não poderá ser clicável e nem dar a entender que pode ser clicada (como está no momento). Somente as abas anteriores devem ser clicáveis.

![1](https://cloud.githubusercontent.com/assets/18294515/20521892/9a3bb0ec-b094-11e6-9779-fd2d863b7ca2.png)

**Comment by marylly** [comment]
@thaisrigolon avaliar, por gentileza.

**Comment by thaisrigolon** [comment]
Ambiente master quebrado...

![1](https://cloud.githubusercontent.com/assets/18294515/20530191/c3aebd32-b0b9-11e6-95eb-d419972bccea.png)

**Comment by thaisrigolon** [comment]
- [x] A página atual em que o usuário está não poderá dar a entender que ele pode clicar como está no momento com o ___________.

![1](https://cloud.githubusercontent.com/assets/18294515/20537245/8a8c7a7a-b0d3-11e6-9ebc-71bdca0e4386.png)

**Comment by marylly** [comment]
Problema corrigido @thaisrigolon.

**Comment by thaisrigolon** [comment]
Obrigada, @marylly.

Mais algumas mudanças que observamos:

- [x] O breadcrumb deve acompanhar a movimentação da página, como o botão EDITAR. É possível?

- [x] O breadcrumb, na tela do agente, está na parte inferior da página. Precisa tirar.
![1](https://cloud.githubusercontent.com/assets/18294515/20571975/b12c965c-b190-11e6-8dfe-214843ed9406.png)

**Comment by intrepidocabral** [comment]
Seria importante congelar o breadcrumb também. Exemplo: 
![captura de tela de 2016-11-23 15 27 07](https://cloud.githubusercontent.com/assets/641411/20572410/7cc24d4c-b192-11e6-913b-3af0950bb6ff.png)

**Comment by marylly** [comment]
A barra que segue o scroll com os botões de Editar é a barra onde as mensagens de erros, notificações e mensagens são exibidos, então tiraria seu propósito @thaisrigolon @robertkapa.

**Comment by intrepidocabral** [comment]
> A barra que segue o scroll com os botões de Editar é a barra onde as mensagens de erros, notificações e mensagens são exibidos, então tiraria seu propósito @thaisrigolon @robertkapa.

ok! sobre essa questão então faz sentido.

**Comment by marylly** [comment]
Está ok este item! @thaisrigolon @robertkapa

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
