### ISSUE TITLE
Busca por entidades: tornar o resultado que aparece à esquerda clicável.

### ISSUE THREAD

**Issue by intrepidocabral** [culturagovbr/mapasculturais_descontinuado#49]
é muito pouco intuitivo clicar nos ícones à direita. O resultado da esquerda deve ser clicável e apresentar uma lista. 

![selecao_024](https://cloud.githubusercontent.com/assets/641411/18206739/5d101cd8-70fe-11e6-9f17-1a61e8425368.png)

![selecao_025](https://cloud.githubusercontent.com/assets/641411/18206743/626bcb8c-70fe-11e6-90d0-c6ebce5fd7aa.png)

**Comment by GustavoVS** [comment]
Nos PRs:

https://github.com/hacklabr/mapasculturais/pull/1019
https://github.com/hacklabr/mapasculturais/pull/1020
https://github.com/hacklabr/mapasculturais/pull/1022
