### ISSUE TITLE
Botao de denúncia/sugestão nas Entidades

### ISSUE THREAD

**Issue by GustavoVS** [culturagovbr/mapasculturais_descontinuado#50]
Possibilidade de usuários sugerirem correções a informações do mapa: botao de denuncia/sugestao nas entidades.

**Comment by uira** [comment]
A pessoa precisa estar logada para fazer denúncias/sugestões?

**Comment by marylly** [comment]
@uira a denúncia/sugestão poderá ser anônima, logado ou não no sistema.

**Comment by marylly** [comment]
@thaisrigolon @GustavoVS poderiam homologar este item, por favor?
Este item tem relação com a issue #24

**Comment by thaisrigolon** [comment]
Está disponível no master ou devel? Em quais locais aparecem esse botão?

**Comment by marylly** [comment]
Está na branch master.


Atenciosamente,


*Marylly Araújo Silva*
Analista de Desenvolvimento Web
São Paulo - SP - Brasil
marylly@hacklab.com.br
http://hacklab.com.br
Tel +55 11 3862 1186
Tel +55 11 2892 0122


2016-12-19 9:45 GMT-02:00 Thaís Rigolon <notifications@github.com>:

**Comment by thaisrigolon** [comment]
Ok, mas onde aparece esse botão?

Espaço
![1](https://cloud.githubusercontent.com/assets/18294515/21314179/b0d83944-c5dc-11e6-8e28-d29d45b27ff7.png)

Agente
![1](https://cloud.githubusercontent.com/assets/18294515/21314206/d4b25732-c5dc-11e6-9528-14aec71f9a16.png)

**Comment by marylly** [comment]
@thaisrigolon efetuamos a habilitação da funcionalidade, podem verificar.

**Comment by thaisrigolon** [comment]
**Contato**
- [x] "E-mail", "tipo" e mensagem" precisam ser campos obrigatórios.
- [x] Após enviar uma mensagem, deve haver a possibilidade de enviar uma nova mensagem sem ter que atualizar a página. Criar um botão para enviar nova mensagem.
![1](https://cloud.githubusercontent.com/assets/18294515/21324375/9e3b2fb8-c608-11e6-83f4-bf88b8c24ee4.png)
- [x] Quando o usuário seleciona para receber cópia da mensagem aparece o email da marylly. Como será essa definição nas demais instalações? Onde configuramos o texto padrão?

**Denúncia**
- [x] Alterar nomenclatura "Denuncia" para "Denunciar"
- [x] "Tipo" e "mensagem" precisam ser campos obrigatórios.

**Comment by marylly** [comment]
> Quando o usuário seleciona para receber cópia da mensagem aparece o email da marylly. Como será essa definição nas demais instalações? Onde configuramos o texto padrão?

Isso é definido no plugin Mailer, ver na documentação: https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_config_plugins.md#qual-será-o-e-mail-de-remetente
@thaisrigolon @GustavoVS

**Comment by marylly** [comment]
> Após enviar uma mensagem, deve haver a possibilidade de enviar uma nova mensagem sem ter que atualizar a página. Criar um botão para enviar nova mensagem.

Isso aqui é realmente necessário? Qual as chances de enviar uma segunda denúncia ou sugestão para a mesma entidade uma seguida da outra? @thaisrigolon

**Comment by thaisrigolon** [comment]
> Isso aqui é realmente necessário? Qual as chances de enviar uma segunda denúncia ou sugestão para a mesma entidade uma seguida da outra? @thaisrigolon

Seria bom se tivéssemos essa possibilidade sim. É muito difícil de ser feita? Não temos como prever quais são as "chances" disso acontecer. Seria uma facilidade para o usuário no caso dele esquecer de enviar alguma informação importante. Mas nos diga se isso impacta muito, sem problemas.

**Comment by marylly** [comment]
@thaisrigolon poderia verificar os ajustes e correções, por gentileza?

**Comment by thaisrigolon** [comment]
**Contato**
- [x] O campo email foi retirado? É importante ter esse campo.
- [x] Os campos "tipo" e "mensagem" não estão como campos obrigatórios.

![1](https://cloud.githubusercontent.com/assets/18294515/21617677/4712cb70-d1ce-11e6-897e-d7ac81bfeefa.png)

- [x] O campo para enviar uma nova mensagem não aparece. Isso foi feito? Estou perguntando porque foi ticado acima.


**Denúncia**
- [x] Os campos "Tipo" e "mensagem" precisam ser obrigatórios. Se eu coloco apenas o tipo a mensagem é enviada e se eu coloco apenas a mensagem sem o tipo também é enviado.

![1](https://cloud.githubusercontent.com/assets/18294515/21617546/ccfead04-d1cd-11e6-823e-5ba0d0ab1a7d.png)

![2](https://cloud.githubusercontent.com/assets/18294515/21617555/da34460a-d1cd-11e6-9c59-2ae96d34c8fd.png)

**Comment by marylly** [comment]
>  O campo email foi retirado? É importante ter esse campo.
Este campo só exibido quando o usuário não está logado, caso contrário é utilizado o e-mail do usuário logado @thaisrigolon

**Comment by thaisrigolon** [comment]
> O campo email foi retirado? É importante ter esse campo.
> Este campo só exibido quando o usuário não está logado, caso contrário é utilizado o e-mail do usuário logado @thaisrigolon

Beleza :)

**Comment by marylly** [comment]
>  O campo para enviar uma nova mensagem não aparece. Isso foi feito? Estou perguntando porque foi ticado acima.

Não existe campo, você fecha a janela de confirmação de envio, e o formulário está limpo e com o botão de envio disponível para enviar uma nova mensagem, existindo a possibilidade enviar conforme solicitado. @thaisrigolon

**Comment by marylly** [comment]
> Os campos "tipo" e "mensagem" não estão como campos obrigatórios.

O servidor estava com cache, reiniciei os serviços e agora está funcionando conforme desejado. @thaisrigolon

**Comment by thaisrigolon** [comment]
- [x] Qual é a referência pra criação dessa lista com os tipos de denúncia?

![1](https://cloud.githubusercontent.com/assets/18294515/21620543/f930596e-d1db-11e6-8936-f9f0a7c655fe.png)

**Comment by marylly** [comment]
> Qual é a referência pra criação dessa lista com os tipos de denúncia?

Segue @thaisrigolon: https://rede.social/Denuncia?desc=Anuncio%2033

**Comment by thaisrigolon** [comment]
> Qual é a referência pra criação dessa lista com os tipos de denúncia?
> Segue @thaisrigolon: https://rede.social/Denuncia?desc=Anuncio%2033

Observamos aqui o site. Vocês poderiam procurar outras referências além dessa?

**Comment by marylly** [comment]
@thaisrigolon não sei de quais referências precisam, mas das solicitações feitas para o core do Mapas, essa lista atende. Tem alguma coisa que está faltando? Precisam de algo? Se quiserem sugerir outras referências, sinta-se a vontade.

**Comment by marylly** [comment]
- [x] Os tipos de denúncia será substituído por uma  listagem mais genérica, e se for necessária outras opções, deverá ser customizado na instalação do Mapas.
Deve conter as seguintes opções:
* Conteúdo ofensivo ou inadequado
* Conteúdo incorreto ou calunioso
* Conteúdo que viola direitos
* Outros

**Comment by marylly** [comment]
Poderia verificar @thaisrigolon ?
Servidor: http://master.map.as

**Comment by thaisrigolon** [comment]
Ok, issue homologada.

**Comment by vitor-kato** [comment]
@marylly 
Há a **possibilidade** de haver bug no envio de email através dos botoes de Denunciar/Contato. Testes feitos na URL do **master** , **rc** e **Mapas do Mato Grosso**, indicam que os emails não estão sendo enviados e quando o usuário marca para receber cópia também não recebe.

**Comment by marylly** [comment]
As configurações na instalação estão habilitadas?
Se for servidor smtp Gmail, tem que liberar o envio de e-mails pelo próprio gmail.
Por favor, qualquer dúvida, consultem a documentação:
https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_config_plugins.md#notificações

https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_config_plugins.md#mailer
@thaisrigolon @vitor-kato

**Comment by vitor-kato** [comment]
@marylly 
No mato grosso pode ser possível que a configuração de email estava errada, lá testamos com smtp Gmail mas não verificamos a configuração do próprio gmail como você disse, porém no ambiente teste **master** e **rc** não eram pra estar configurado corretamente?

**Comment by diegodorgam** [comment]
@marcus2703 fizemos alguns testes com relação ao envio de e-mails e no ambiente de teste funciona usando o gmail. 
Podemos marcar um momento com a equipe de infra para debugar isso em produção?
Assim podemos verificar a hipótese de esse envio estar sendo bloqueado internamente, por sistema do zimbra ou pelo firewall mesmo.

**Comment by thaisrigolon** [comment]
@marcus2703 poderia responder o comentário do @diegodorgam para finalizarmos essa issue? ^

**Comment by marcus2703** [comment]
@diegodorgam acho válido alinharmos esses testes.
Preciso agendar com a equipe de infra aqui do MinC. Para quando teríamos essa disponibilidade?

**Comment by diegodorgam** [comment]
Quando quiser @marcus2703, eu estou à disposição com o @rafaelchavesfreitas , quanto antes melhor.

**Comment by diegodorgam** [comment]
Resolvido gente, 

para conseguir enviar um email de dentro do server de homologação usamos a configração:
```
        'mailer.user' => "",
        'mailer.psw'  => "",
        'mailer.protocol' => 'tls',
        'mailer.server' => 'RELAYSMTPADDRESS',
        'mailer.port'   => '25',
        'mailer.from' => 'noreply@cultura.gov.br',
```

Foi preciso configurar o servidor de SMTP com relay no server de homologação;
Trocar o protocolo para `tls` -- padrão era `ssl`
e liberar o envio no firewall do minc que estava barrando.

![captura de tela 2017-05-16 as 19 41 16](https://cloud.githubusercontent.com/assets/12052193/26131391/1706fd06-3a70-11e7-8801-861124e48452.png)

Agora é só reproduzir essa conf em produção.

Mas antes de alterarem a configuração, vamos fechar a #96 .
