### ISSUE TITLE
Textos das seções do SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#54]
# Seção Textos
- [x] Nesta seção você configura os textos utilizados na interface do site. Cada texto tem uma explicação do local em que deverá aparecer a informação. A opção de “exibir opções avançadas” possibilita que outros campos apareçam para definição dos textos.

# Seção Entidades
- [x] Nesta seção você configura as entidades que estarão habilitadas na instalação e as cores para cada uma das entidades.

# Seção Imagens
- [x] Nesta seção você configura as imagens que vão aparecer na instalação. É possível selecionar o logo da instalação, o background e o logo da instituição.

# Seção Mapa
- [x] Nesta seção você indica a posição inicial do mapa, ou seja, quando o usuário abrir o mapa ele visualizará as informações nessa posição já estabelecida podendo fazer um zoom mínimo e máximo. Informe o endereço/nome município/nome estado no campo “Digite um endereço”.

**Comment by marylly** [comment]
@thaisrigolon vai manter o texto da seção de filtros?

**Comment by thaisrigolon** [comment]
Sim, pode manter @marylly

**Comment by marylly** [comment]
@thaisrigolon concluído. Posso encerrar?

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
