### ISSUE TITLE
Seção Imagens - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#56]
- [x] É necessário informar qual é o tamanho padrão da imagem do background para aparecer com boa resolução no subsite e indicar que a imagem do background deve ser com transparência, sem fundo.

**Comment by marylly** [comment]
@thaisrigolon poderia verificar, por gentileza?

**Comment by thaisrigolon** [comment]
Obrigada, agora está ok.
