### ISSUE TITLE
Seção Entidades - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#57]
As cores da "Introdução" e "Desenvolvedores" na página inicial também deveriam estar disponíveis na seção de "Entidades" para o usuário informar qual é a cor de cada uma das partes. No momento, não temos como escolher a cor e sempre será igual para todos os subsites:

![0](https://cloud.githubusercontent.com/assets/18294515/20969334/b0291f2a-bc6f-11e6-930f-3bac24972c13.png)

![1](https://cloud.githubusercontent.com/assets/18294515/20969333/b026df12-bc6f-11e6-9428-2e87833cda40.png)

**Comment by marylly** [comment]
Poderia verificar este item @thaisrigolon, por gentileza?

**Comment by thaisrigolon** [comment]
Está ok, obrigada.
