### ISSUE TITLE
Página "Como Usar" - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#60]
Na configuração do SaaS é preciso ter a possibilidade de configurar os textos e imagens da página "Como usar". Além de poder trocar o arquivo "manual completo" da instalação.

![1](https://cloud.githubusercontent.com/assets/18294515/21777921/4c590202-d688-11e6-9cb0-5cb16d561a97.png)

**Comment by marylly** [comment]
Solução será contemplada na issue #62

**Comment by marylly** [comment]
Exemplo do conteúdo em Markdown:
[conteudo.docx](https://github.com/culturagovbr/mapasculturais/files/748391/conteudo.docx)

**Comment by thaisrigolon** [comment]
Já existe um campo pra configurar o conteúdo da página "Como usar"?

**Comment by marylly** [comment]
Sim, na aba _Textos_, dentro de **exibir opções avançadas** @thaisrigolon.

**Comment by marylly** [comment]
@thaisrigolon no arquivo anexado conteudo.docx tem exemplos de como usar imagens no conteúdo Markdown.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
