### ISSUE TITLE
Imagens - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#61]
- [x] É preciso ter um campo na aba Imagens para alterar o favicon:
![icone](https://cloud.githubusercontent.com/assets/18294515/21779372/88ee9ef6-d68e-11e6-9465-a0eb9e0bd5be.png)

- [x] A imagem padrão da capa das entidades, no momento, é a imagem do logo da Instituição. É preciso ter um campo para subir essa imagem de capa e se o usuário não colocar nenhuma imagem o default deve ser apenas a cor da entidade.
![1](https://cloud.githubusercontent.com/assets/18294515/21859490/ebb2669a-d813-11e6-8b35-37259ef93f31.png)

- [x] Tirar a imagem default que está no momento. No caso de usuários que não quiserem ter uma imagem de fundo eles serão obrigados a colocar alguma imagem para essa default sair.
![1](https://cloud.githubusercontent.com/assets/18294515/21779403/b3ecadfa-d68e-11e6-9042-530149ae6214.png)

**Comment by marylly** [comment]
Correção disponível em http://master.map.as @thaisrigolon @GustavoVS @robertkapa

**Comment by thaisrigolon** [comment]
Marylly, o Gustavo atualizou o o branch RC do MinC, mas não apareceram essas alterações para teste.

**Comment by marylly** [comment]
@thaisrigolon preciso de detalhes das dúvidas sobre as imagens, se não está claro na documentação, podemos melhorar ser for necessário.

**Comment by thaisrigolon** [comment]
Ok. Issue homologada.
