### ISSUE TITLE
Markdown - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#62]
Durante os testes evidenciamos a necessidade de alguns campos terem um markdown para facilitar a escrita do texto quando o usuário quiser colocar em negrito, inserir links, etc. Além de ter nesse markdown uma função de adicionar imagens. Por exemplo, no campo **descrição do site** não conseguimos inserir logos e nessa página é fundamental adicionar o logo do Instituto TIM e da Secretaria. O que vocês sugerem?

- O markdown do github é uma referência. Outra referência: http://plnkr.co/AFxN7uiwkZlJ9OMZwXey

![1](https://cloud.githubusercontent.com/assets/18294515/21804837/27e4eea0-d718-11e6-81d3-b56c6d421965.png)

**Comment by marylly** [comment]
@thaisrigolon @robertkapa @GustavoVS precisamos levantar todos os campos que precisam de Markdown nessa situação, isso é possível?

**Comment by marylly** [comment]
@thaisrigolon @robertkapa @GustavoVS é possível vocês  arranjarem algum conteúdo em markdown que utilize o máximo de recursos e tags HTML para testarmos as opções de editores markdown? Vai ajudar a elegermos o melhor componente para resolver esta issue.

**Comment by thaisrigolon** [comment]
Segue arquivo com conteúdo em markdown: [Conteúdo.docx](https://github.com/culturagovbr/mapasculturais/files/739287/Conteudo.docx)

**Comment by GustavoVS** [comment]
- [x] Descrição do site
- [x] Texto da seção "agentes" da home
- [x] Texto da seção "espaços" da home
- [x] Texto da seção "projetos" da home
- [x] Texto da seção "desenvolvedores" da home
- [x] Texto de boas-vindas

**Comment by marylly** [comment]
Este ajuste se encontra na branch rc e contempla as issues #60 #71.
@thaisrigolon @GustavoVS

**Comment by marylly** [comment]
Exemplo de conteúdo utilizando o Markdown:
[conteudo.docx](https://github.com/culturagovbr/mapasculturais/files/748383/conteudo.docx)

**Comment by marylly** [comment]
Documentação de apoio a geração de conteúdo utilizando o Markdown: https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_config_saas.md#aba-textos-da-instalação

**Comment by thaisrigolon** [comment]
@marylly, tudo está funcionando no markdown. Só na parte de subir uma imagem na seção downloads e depois conseguir inserir no markdown que está mais complicado. Poderia explicar o passo-a-passo?
![1](https://cloud.githubusercontent.com/assets/18294515/22753871/c434e3e6-ee24-11e6-8e76-66c114d9ca0d.png)

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
