### ISSUE TITLE
SaaS - Atribuição roles saasAdmin e saasSuperAdmin via agente

### ISSUE THREAD

**Issue by GustavoVS** [culturagovbr/mapasculturais_descontinuado#63]
Não é possível atribuir as roles **saasAdmin** e **saasSuperAdmin** para outros usuários, só é possível através do banco.

![image](https://cloud.githubusercontent.com/assets/7750643/21860435/b2eb139e-d817-11e6-899d-da28f45f2e5e.png)

**Comment by marcus2703** [comment]
Atualmente o tema do Cultura Viva requer que o grupo que faz a validação dos dados do ponto de cultura via plataforma tenham acesso ao sistema com permissão de Admin na tabela roles.
Com o uso da plataforma do SaaS, isso poderá gerar um problema permitindo que usuários não habilitados consigam acessar as configurações de edição dos subsites no SaaS.

**Comment by marylly** [comment]
@GustavoVS somente usuário com role saasSuperAdmin pode atribuir saasAdmin. Precisamos criar uma forma de atribuir a role sem ser pelo agente, o que não causa o problema mencionado pelo @marcus2703  no comentário acima.

**Comment by GustavoVS** [comment]
Pela regra que temos, o melhor mantermos a criação de saasSuperAdmin diretamente pelo banco mesmo.
