### ISSUE TITLE
Arrumar link do "Logo Instituição" - SaaS

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#66]
Link aponta para # relativo de onde está, gerando o erro abaixo se estiver em alguma das entidades do Mapas.
![erro_link_logo_instituicao](https://cloud.githubusercontent.com/assets/12901157/22121122/628b98f6-de61-11e6-881f-f0a0da8da8c9.png)

**Comment by marylly** [comment]
Correção disponível em http://master.map.as @thaisrigolon @GustavoVS @robertkapa

**Comment by GustavoVS** [comment]
@marylly quando coloquei no branch master basicamente quebrou.. creio que por outras coisas que estão no master.

Você pode colocar em algum outro branch mais 'limpo' ou criar um novo a partir do v2 (que é o que estamos usando) com as alterações?

**Comment by marylly** [comment]
@GustavoVS houve uma grande correção no core por causa dos arquivos da plataforma, acredito que agora será possível efetuar este teste.

**Comment by GustavoVS** [comment]
@marylly não conseguimos continuar os testes após colocar no master. Basicamente:
Temas personalizados não carregam
Temas customizados (SNIIC, Museus, Bibliotecas) carregam mas ficam exibindo url antes de carregar a página e ficam com a barra do menu estranha.

Gravei um pequeno vídeo para mostrar isso :D

https://www.youtube.com/watch?v=TSpE_RtPX1k&feature=youtu.be

**Comment by marylly** [comment]
@GustavoVS o erro que ocorre no Theme.php é porque é necessário executar a atualização de pacotes como mencionei na issue #69.

sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev php-imagick

**Comment by thaisrigolon** [comment]
Marylly, o Gustavo atualizou o branch RC do MinC com a execução dessa atualização de pacotes, mas não apareceram essas alterações para teste.

**Comment by marylly** [comment]
@thaisrigolon poderiam verificar essa issue, por gentileza?

**Comment by marcus2703** [comment]
@marylly @thaisrigolon testei aqui a modificação. Ela corrigiu o erro reportado.
Mas precisamos de um campo para definir a URL que será aberta ao clicar na imagem. Ela está abrindo uma nova janela do Mapas em questão (usando a url do subsite).

**Comment by marylly** [comment]
Campo disponível na aba **Textos** na seção **Página Inicial**. @thaisrigolon @marcus2703. Disponível na branch rc, sendo possível testar em http://rc.map.as

**Comment by GustavoVS** [comment]
@marylly está dando erro ao atualizar para o branch RC:

![selecao_019](https://cloud.githubusercontent.com/assets/7750643/23622222/99ba0828-027c-11e7-9fce-8df36827a16c.png)

Antes do erro na página, também aparecem esses erros no deploy.sh (PHP Fatal error:  Call to a member function getRevisionData() on a non-object in /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntityRevision.php on line 137):

![selecao_020](https://cloud.githubusercontent.com/assets/7750643/23622273/c4ee7e2a-027c-11e7-8332-db9c711dd7de.png)

**Comment by thaisrigolon** [comment]
Testamos no ambiente de teste e está ok.
@marcus2703 , podemos fazer o deploy?

**Comment by marcus2703** [comment]
Não está aparecendo o campo de URL na aba TEXTOS > PÁGINA INICIAL. Testei no http://saas.mapas.cultura.gov.br

**Comment by marcus2703** [comment]
Testei com sucesso a solução.
Utilizei o servidor http://dev.saas.mapas.cultura.gov.br no teste de configuração. 
No teste utilizei a instância http://jaguarao.dev.saas.mapas.cultura.gov.br/ abriu com sucesso a URL configurada em uma nova janela.
