### ISSUE TITLE
Erro ao carregar 2 instâncias simultâneamente - SaaS

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#67]
Quando carregamos 2 instâncias do SaaS simultaneamente está gerando erro na visualização das informações. Carrega os dados da primeira instância a ser carregada no lugar dos dados originais de uma determinada instância.
![erro_cache](https://cloud.githubusercontent.com/assets/12901157/22121584/6f994c08-de63-11e6-926d-afb583d8aa6a.png)

**Comment by marylly** [comment]
Erro corrigido na reescrita da API para melhora de performance que está em processo de homologação. @GustavoVS @robertkapa @thaisrigolon #22

**Comment by GustavoVS** [comment]
Então, vamos testar assim que o refactor da API tiver sido homologada no branch **RC** e for mergeada para o branch **V2**.

**Comment by marcus2703** [comment]
Testes de carregamento de 02 instâncias realizados, tentei refazer o erro acima descrito sem sucesso.
Dados exibidos corretamente dentro de cada instância. Correção está ok.
