### ISSUE TITLE
Entidades na cor config padrão - SaaS

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#69]
As entidades das instâncias no SaaS são exibidas no mapa na cor da instância padrão do SaaS. Não sendo exibidas na cor escolhida pelo tema.

![cor_entidade](https://cloud.githubusercontent.com/assets/12901157/22122575/3fc6d9b0-de67-11e6-8879-57ea3b632294.png)

**Comment by marylly** [comment]
Correção disponível em http://master.map.as. @thaisrigolon @GustavoVS @robertkapa

Esta atualização exige a instalação de algumas bibliotecas de imagem:

sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev php-imagick

**Comment by GustavoVS** [comment]
@marylly efetuei o teste no branch **RC**, instalei as bibliotecas mas o problema persiste

**Comment by thaisrigolon** [comment]
Testamos aqui e temos as seguintes considerações:

- [x] A configuração das cores das entidades deve ser alterada para todas não só para Agentes como está no momento. Ou seja, Eventos, Espaços e Projetos também precisam ter a mesma cor configurada no painel do SaaS.
- [x] No mapa está mostrando os agentes e a cor certa só ficou quando tinha apenas 1 agente no mapa. A partir de 2 agentes voltava pra cor padrão (azul).
![agentes](https://cloud.githubusercontent.com/assets/18294515/22475130/208f1a5a-e7c5-11e6-9f2f-051acf252ddc.png)

- [x] O ícone do agente não está aparecendo quando tem apenas 1 agente. A bolinha está com o centro em branco. 
![pin](https://cloud.githubusercontent.com/assets/18294515/22475197/5b5a2bd4-e7c5-11e6-8e77-d1ae94fb12e5.png)

**Comment by marylly** [comment]
Vocês limparam o cache do navegador?
Dependendo do servidor, ele tem cache também que podem influenciar em carregar as imagens antigas. @thaisrigolon @GustavoVS

**Comment by marylly** [comment]
Correções disponíveis para testes @thaisrigolon @GustavoVS

**Comment by thaisrigolon** [comment]
Só está pendente alterar a cor dos ícones da entidade **Espaço** no mapa:

![1](https://cloud.githubusercontent.com/assets/18294515/22754113/8d7f42a0-ee25-11e6-9179-12cbd41bea2d.png)

**Comment by marylly** [comment]
@thaisrigolon poderiam verificar essa questão? Não se esqueçam de limpar o cache do servidor e do navagador para a conversão da cor dos pins aconteçam.

**Comment by thaisrigolon** [comment]
@marylly não é cache. Acabei de verificar novamente e só a entidade **Espaço** continua com as cores dos pin's diferentes:

Instalação: http://es.dev.saas.mapas.cultura.gov.br

![1](https://cloud.githubusercontent.com/assets/18294515/22978357/966beac2-f379-11e6-8a1d-0e38108ab48d.png)

![2](https://cloud.githubusercontent.com/assets/18294515/22978364/9a7ca854-f379-11e6-8ab7-261752aaad82.png)

![3](https://cloud.githubusercontent.com/assets/18294515/22978365/9d2b1ed2-f379-11e6-9927-44c980485e83.png)

**Comment by marylly** [comment]
O ambiente do ES está no RC ou no V3 @thaisrigolon ? Testei nos servidores de testes da branch rc, é está funcionando para nós a conversão das cores dos ícones de espaços. http://rc.map.as

**Comment by thaisrigolon** [comment]
O ambiente do ES está no V3, @marylly. A branch V3 está com esta conversão das cores no espaço?

**Comment by marylly** [comment]
@thaisrigolon é a _branch_ **v3** é a versão estável do mapas. Antes de estarem homologados ou pendentes de ajustes, ficam disponíveis na _branch_ **rc**.

**Comment by thaisrigolon** [comment]
@marylly este erro ainda persiste, tanto no branch **rc** como no **v3**

**Comment by diegodorgam** [comment]
@marcus2703 fizemos os testes com o @avaloni e no ambiente de testes dele funciona a alteração de cor do pin.
Será que conseguimos marcar uma hora para fazer um debug, tipo trazer as configurações do ambiente do minc para o ambiente de testes local para conseguirmos debugar?

**Comment by thaisrigolon** [comment]
@marcus2703 poderia responder o comentário do @diegodorgam para finalizarmos essa issue? ^

**Comment by marcus2703** [comment]
@diegodorgam de qual ambiente estão falando? RC ou local?

**Comment by diegodorgam** [comment]
Precisamos de acesso ao ambiente RC do minc, para copiar as configurações.

**Comment by thaisrigolon** [comment]
@diegodorgam vocês estão com acesso agora, né?

**Comment by diegodorgam** [comment]
Estamos com acesso o/
Vamos trabalhar nessa issue em breve, Marcus pediu pra priorizar as issues do cultura viva

**Comment by diegodorgam** [comment]
fiz os testes e parece que está funcionando @marcus2703 e @thaisrigolon

**Comment by marcus2703** [comment]
Após a atualização ontem ainda estão apresentando cores diferentes nos espaços. Mostra a cor padrão do Mapas

**Comment by diegodorgam** [comment]
Fiz esse teste hoje @marcus2703 :

<img width="1275" alt="captura de tela 2017-05-26 as 11 48 17" src="https://cloud.githubusercontent.com/assets/12052193/26499607/a4974ec8-4209-11e7-976e-62b52fb2ab93.png">

<img width="1276" alt="captura de tela 2017-05-26 as 11 47 59" src="https://cloud.githubusercontent.com/assets/12052193/26499543/76c027f4-4209-11e7-9e88-62032ca4b84f.png">

<img width="1276" alt="captura de tela 2017-05-26 as 11 47 43" src="https://cloud.githubusercontent.com/assets/12052193/26499542/76bfe96a-4209-11e7-8d51-646e25d4261f.png">

o que está de errado nas cores?

**Comment by diegodorgam** [comment]
erro encontrado e reproduzido na URL:
http://mapacultural.es.gov.br/busca/##(global:(enabled:(space:!t),filterEntity:space))

Onde os pins dos espaços estão com cor diferente do header.

**Comment by diegodorgam** [comment]
@rafaelchavesfreitas o ambiente está reproduzido em http://es.dev.saas.mapas.cultura.gov.br/
o erro está no ajuste de cor do Pin dos Espaços.
o Theme que está sendo usado é o Subsite, mas a princípio as cores parecem estar sendo gravadas no banco de dados

consegue dar uma olhada?

**Comment by diegodorgam** [comment]
Resolvido, o bug estava relacionado a existência de acentos nas chaves `entidades_relacionadas`, como o server estava com o locale en_US ele gravava a chave com um caracter quebrado no banco, o que bugava a relação entre a chave e o Pin nos assets. 
Na versão 3.1.3 disponível no repositório do hacklab foram inseridos os commits para corrigir as chaves e passar elas para ingles.

para corrigir em outras instalações ou nos forks, basta puxar a versão 3.1.3 e rodar o /scripts/db-updates.sh.

o novo código já está disponível no server de teste e de homologação.
