### ISSUE TITLE
Opção exibir agentes e espaços juntos não funciona - SaaS

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#70]
Ao selecionar a opção "Mostrar" no canto inferior direito, quando tentamos visualizar tanto agentes quanto espaços na mesma aba, não está mostrando a entidade selecionada posteriormente.
Cliquei na guia "Espaços", depois na opção de mostrar selecionei "Mostrar Agentes". e não exibiu os agentes.

![exibir_ag_sp_juntos](https://cloud.githubusercontent.com/assets/12901157/22122871/42e9325e-de68-11e6-9a0c-ed40ee0727f2.png)

**Comment by marylly** [comment]
Correção disponível em http://master.map.as @thaisrigolon @GustavoVS @robertkapa

**Comment by GustavoVS** [comment]
@marylly quando coloquei no branch master basicamente quebrou.. creio que por outras coisas que estão no master.

Você pode colocar em algum outro branch mais 'limpo' ou criar um novo a partir do v2 (que é o que estamos usando) com as alterações?

**Comment by marylly** [comment]
@GustavoVS houve uma grande correção no core por causa dos arquivos da plataforma, acredito que agora será possível efetuar este teste.

**Comment by GustavoVS** [comment]
@marylly não conseguimos continuar os testes após colocar no master. Basicamente:
Temas personalizados não carregam
Temas customizados (SNIIC, Museus, Bibliotecas) carregam mas ficam exibindo url antes de carregar a página e ficam com a barra do menu estranha.

Gravei um pequeno vídeo para mostrar isso :D

https://www.youtube.com/watch?v=TSpE_RtPX1k&feature=youtu.be

**Comment by GustavoVS** [comment]
@marylly foi feito um push para o branch **RC**, mas o filtro da parte inferior não funcionou

**Comment by marylly** [comment]
@GustavoVS sobre qual filtro você fala? Poderia ser mais especifíco?

**Comment by GustavoVS** [comment]
O que o Marcus reportou na primeira imagem..
![exibir_ag_sp_juntos](https://cloud.githubusercontent.com/assets/12901157/22122871/42e9325e-de68-11e6-9a0c-ed40ee0727f2.png)

**Comment by marcus2703** [comment]
Teste realizado.
Correção realizada com sucesso.
