### ISSUE TITLE
HTML - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#71]
Após salvar um texto em html e publicá-lo na página, se um usuário quiser atualizar o html do campo e retornar para atualizar a informação do texto, percebemos que todo o código foi perdido e só resta o texto sem nada do html:

![1](https://cloud.githubusercontent.com/assets/18294515/22214693/bd04d29a-e17f-11e6-89c9-77fa7b8c56ae.png)

![2](https://cloud.githubusercontent.com/assets/18294515/22214716/d9c0990a-e17f-11e6-93dc-41681f505c86.png)

**Comment by marylly** [comment]
Agora este conteúdo será em Markdown, não utilizar a notação em HTML,  e o código em sintaxe não será mais perdido como acontecia anteriormente. @thaisrigolon @GustavoVS

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
