### ISSUE TITLE
Botão excluir - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#72]
Após excluir um SaaS que estava na aba **ativo**, o SaaS vai automaticamente para a aba **lixeira**. Nesta aba deveria ter o botão _excluir_ para dar a possibilidade de excluir o SaaS definitivamente. No entanto, esse botão aparece somente para algumas instalações e deveria aparecer para todas:

![1](https://cloud.githubusercontent.com/assets/18294515/22253390/92d82a44-e238-11e6-90aa-e894dd96fb88.png)

**Comment by marylly** [comment]
@thaisrigolon @robertkapa @GustavoVS essa situação é porque o usuário que estava acessando neste exemplo, não é proprietário da instalação SaaS, então ele não tem permissões para excluir a instalação. Tem que ser o dono (owner) da instalação ou um usuário saasSuperAdmin.

**Comment by thaisrigolon** [comment]
Ok.

**Comment by thaisrigolon** [comment]
@marylly eu e o @marcus2703 estamos acessando o ambiente de produção com usuários SaaSAdmin e não conseguimos excluir definitivamente algumas instalações:

![erro](https://cloud.githubusercontent.com/assets/18294515/22985067/7078dda6-f38e-11e6-88b1-83a1ef79ec88.png)

**Comment by marylly** [comment]
Reforçando que só o usuário com role _superSaasAdmin_ tem acesso de excluir qualquer instalação definitivamente, se a opção não está surgindo, pode ser que vocês não sejam os **Publicadores**/**Responsáveis** pelas instalações que não exibem o botão de exclusão definitiva. @thaisrigolon @marcus2703

**Comment by marcus2703** [comment]
Sim @marylly. Meu usuário do SaaS é  "saasSuperAdmin".
E mesmo assim não conseguimos excluir os subsites.
Acho que talvez seja uma confusão na exibição. Pois no exemplo acima você pode ver que a instalação do Museus aparece na lixeira, sendo uma instalação ativa.
Ocorre isso também na aba rascunho e arquivados. Temos instalações ativas nessas abas também.

**Comment by thaisrigolon** [comment]
@marylly mais um erro ao tentar excluir definitivamente o SaaS em produção:

Ao clicar no botão excluir definitivamente ocorreu o erro:

![1](https://cloud.githubusercontent.com/assets/18294515/23212966/dabb98ee-f8e7-11e6-97cf-15d59419211d.png)

**Comment by thaisrigolon** [comment]
@marylly 

E não consigo criar outro subsite com a mesma URL enquanto não excluo definitivamente esse:

![1](https://cloud.githubusercontent.com/assets/18294515/23213041/34621648-f8e8-11e6-8611-09e78b396760.png)

**Comment by marylly** [comment]
> Ao clicar no botão excluir definitivamente ocorreu o erro:

@thaisrigolon @GustavoVS está dando erro porque está tentando excluir os registros relacionados. Será que é prudente criar a deleção para apagar o subsite? porque os relacionamentos do banco de dados no exige que apaguemos todo o conteúdo do subsite o que incluí: Agentes/Espaços/Projeto/Eventos/Selos/Permissões de Usuários/, isso dá poder para algum usuário apagar uma instalação inteira, o que é bem preocupante. Será que podemos deixar a instalação apenas na lixeira ou arquivada?
Essa questão de criar uma instalação com a mesma url de outro subsite já existente eu posso ignorar a validação para verificar apenas as instalações ativas. O que acham?

**Comment by marcus2703** [comment]
@marylly é possivel que as informações das entidades permaneçam na instalação "master" que é o MapasBr, ao invés de serem excluídas?
Atualmente todas as informações aparecem no MapasBr, e este é um dos objetivos do SaaS. Entendo que se em um determinado momento um subsite vir a ser excluído, suas informações deveriam permanecer.

**Comment by marylly** [comment]
@thaisrigolon @marcus2703 poderiam verificar, por gentileza? Está na _branch_ **rc**.

**Comment by GustavoVS** [comment]
@marylly está dando erro ao atualizar para o branch RC:

![selecao_019](https://cloud.githubusercontent.com/assets/7750643/23622222/99ba0828-027c-11e7-9fce-8df36827a16c.png)

Antes do erro na página, também aparecem esses erros no deploy.sh (PHP Fatal error:  Call to a member function getRevisionData() on a non-object in /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntityRevision.php on line 137):

![selecao_020](https://cloud.githubusercontent.com/assets/7750643/23622273/c4ee7e2a-027c-11e7-8332-db9c711dd7de.png)

**Comment by marylly** [comment]
@GustavoVS foram reiniciados os serviços e gerados novamente os caches?

**Comment by thaisrigolon** [comment]
Está disponível para teste. @marcus2703 poderia verificar se está ok?

**Comment by thaisrigolon** [comment]
> @marylly é possível que as informações das entidades permaneçam na instalação "master" que é o MapasBr, ao invés de serem excluídas?
> Atualmente todas as informações aparecem no MapasBr, e este é um dos objetivos do SaaS. Entendo que se em um determinado momento um subsite vir a ser excluído, suas informações deveriam permanecer.

É possível, @marylly?

**Comment by marcus2703** [comment]
Ainda estão aparecendo em todas as abas as listas de subsites ativos. O que torna muito complexo o uso deste painel no sentido de excluir subsites. 
Acredito que os substites ativos deveriam aparecer somente nesta aba, e assim respectivamente. Facilitando a manutenção e organização.
Ainda não ficou claro se o subsite irá "desaparecer" de alguma lista.
Eu criei um subsite de teste, e após excluir ele, ele aparece na aba Lixeira, e só tem as opções "editar" e "recuperar"
![image](https://cloud.githubusercontent.com/assets/12901157/24772232/e3326356-1ae6-11e7-87d9-4f8227e79c84.png)

**Comment by avaloni** [comment]
> Ainda estão aparecendo em todas as abas as listas de subsites ativos. O que torna muito complexo o uso deste painel no sentido de excluir subsites.

Alteração realizada na branch **RC** deste repositório.

> Eu criei um subsite de teste, e após excluir ele, ele aparece na aba Lixeira, e só tem as opções "editar" e "recuperar"

Na branch **RC** está normal,  mas só usuários "superSaasAdmin" conseguem excluir definitivamente.

**Comment by marcus2703** [comment]
Testes efetuados.
Exclusão realizada.
Em relação a situação do subsite id ser atualizado com valor null, seria possivel que ao excluir o sistema solicite para qual instalação os objetos criados devem ser repassados?
Ou ainda, que a instalação definida como Master fosse a MapasBR no caso do MinC, colocar um campo com essa informação.
Tipo, nas abas dos subsites, ter uma checkbox com uma flag de instalação principal.
Preocupa-me este campo ficar vazio

**Comment by intrepidocabral** [comment]
> Em relação a situação do subsite id ser atualizado com valor null, seria possivel que ao excluir o sistema solicite para qual instalação os objetos criados devem ser repassados?

Isso é uma nova funcionalidade não prevista nesse escopo. Vamos deixar ela em standby para ser realizada postumamente numa renovação de parcerias. =)

**Comment by diegodorgam** [comment]
sim é possível substitutir o id pelo id de outro subsite ao invés de manter ele como null, mas isso é uma nova funcionalidade como disse o @photonauta35, vai exigir um esforço que está além do escopo fechado, podemos negociar ela dentro de um novo escopo.
Sugiro que essa issue seja fechada e que seja aberta em uma nova issue com essa demanda, caracterizada como uma evolução da funcionalidade.

**Comment by thaisrigolon** [comment]
@marcus2703 vou fechar esta issue porque foi corrigido, ok?
Por favor, abra uma nova issue com essa demanda pra incluirmos no novo escopo.
