### ISSUE TITLE
Agentes no Painel de Controle - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#73]
Quando eu faço login direto na instalação do Espírito Santo e estou no meu painel de controle vejo que tenho apenas 1 agente, mas quando clico no número 1 abre a lista com dois agentes:

![1](https://cloud.githubusercontent.com/assets/18294515/22438761/4d5162fc-e714-11e6-9e84-695fdd9e8f2c.png)

![2](https://cloud.githubusercontent.com/assets/18294515/22438768/4fce7df8-e714-11e6-80c1-6897a3bf1cfe.png)

**Comment by marylly** [comment]
@thaisrigolon, o usuário principal deve estar com _status_ de **Rascunho**, mas como ele é o principal do login do usuário, ele aparece na primeira aba e não na aba **Rascunho**. Após a publicação do agente, a contagem ficará correta.

**Comment by thaisrigolon** [comment]
Agora apareceu da forma correta, mas não fiz nenhuma alteração por aqui...:

![1](https://cloud.githubusercontent.com/assets/18294515/22736340/c32fc460-ede4-11e6-833c-0960546f6bbe.png)

**Comment by marylly** [comment]
@thaisrigolon após preencher as informações do usuário recém cadastrado, você clicou em **Publicar**?
Pode ser isso, porque se você deixar o cadastro incompleto, ficará como _rascunho_, como expliquei anteriormente.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
