### ISSUE TITLE
Favicon - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#75]
Enquanto a imagem do Favicon não foi adicionada na instalação do SaaS o seguinte erro aparecia antes de carregar a página:

![0](https://cloud.githubusercontent.com/assets/18294515/22474052/fc4db096-e7c1-11e6-96ec-97443187b4ce.png)

![1](https://cloud.githubusercontent.com/assets/18294515/22474056/00dfe3c2-e7c2-11e6-8bcb-af3e6f354994.png)

E na barra das entidades fica com uma parte estranha embaixo:

![barra](https://cloud.githubusercontent.com/assets/18294515/22474156/4580a962-e7c2-11e6-8585-724f8c967368.png)

Isso não pode ocorrer porque se o usuário quiser deixar a imagem default do Mapas a instalação não pode gerar esse erro toda vez ao carregar a página.

Só quando é adicionado o Favicon o erro para de ocorrer:

![3](https://cloud.githubusercontent.com/assets/18294515/22474348/b0bebbe2-e7c2-11e6-92cc-76f5ff8d01a6.png)

**Comment by marylly** [comment]
Não consegui simular esse problema localmente nem nos ambientes de testes das urls http://master.map.as http://rc.map.as  o espaçamento e nem da url da imagem @thaisrigolon @GustavoVS

**Comment by GustavoVS** [comment]
@marylly eu consegui replicar no rc.map.as, é só acessar essa URL aqui: http://testex.rc.map.as

Me pareceu que o erro só começou depois que eu coloquei alguma cor nas entidades do Subsite, mas depois de eu ter tirado as cores das Entidades continuou apresentando esse problema

**Comment by marylly** [comment]
Poderiam verificar essa questão @GustavoVS ?

**Comment by thaisrigolon** [comment]
Ok. Issue homologada.
