### ISSUE TITLE
SaaS - Atribuição de Super Administradores

### ISSUE THREAD

**Issue by GustavoVS** [culturagovbr/mapasculturais_descontinuado#76]
Ao efetuar o teste usando o branch RC, a atribuição de Super Administradores/Administradores não funciona.
Ao pesquisar o agente, atribuir e salvar parece que funciona normalmente, mas ao sair e voltar da página o agente que foi atribuido desaparece.

**Comment by marylly** [comment]
@GustavoVS poderiam verificar, por gentileza?
