### ISSUE TITLE
Aba Login Cidadão - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#78]
Apenas usuários **SaaSadmin** podem ter acesso à aba do Login Cidadão: 

![1](https://cloud.githubusercontent.com/assets/18294515/22592137/5db76fe0-e9ff-11e6-9de4-e85d7d81e675.png)

Usuários com perfil **Super Administrador** e **Administrador** não precisam ver essa aba porque é uma configuração feita pelo SaaSadmin e não pode haver possibilidade de ser alterada por outros usuários impossibilitando o acesso à instalação.

**Comment by marylly** [comment]
@thaisrigolon poderiam verificar, por gentileza?

**Comment by vitor-kato** [comment]
- Como Super Admin ainda é possível ver a aba do Login cidadão

![mapa cultural es - espirito santo - dev saas mapas - chromium_014](https://cloud.githubusercontent.com/assets/21978887/23279736/272b1c82-f9f5-11e6-9fd1-0e3b98dc5a61.png)

- E como Admin não é possível ver o painel do subsite

![mapa cultural es - - chromium_015](https://cloud.githubusercontent.com/assets/21978887/23279954/08f9d662-f9f6-11e6-9f41-c8998336b9a9.png)

@GustavoVS @thaisrigolon @marylly

**Comment by marylly** [comment]
Por favor, ler a documentação sobre os perfis do Mapas:
https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_user_profiles.md @thaisrigolon @GustavoVS

**Comment by vitor-kato** [comment]
@marylly 
Eu entendo que o admin não era pra ver a configuração do subsite então isso está OK. Porém para o super admin não é para ser possível ver a aba do Login Cidadão, então o bug ainda não foi corrigido.

**Comment by marylly** [comment]
@vitor-kato o usuário Super admin é o que administra e inclusive define quem será usuário com perfil admin.

**Comment by vitor-kato** [comment]
@marylly  Eu estou me referindo ao problema original apontado pela @thaisrigolon: 
"Usuários com perfil **Super Administrador** e **Administrador** não precisam ver essa aba porque é uma configuração feita pelo SaaSadmin e não pode haver possibilidade de ser alterada por outros usuários impossibilitando o acesso à instalação."
"Apenas usuários **SaaSadmin** podem ter acesso à aba do Login Cidadão"

Porém quando eu realizei o teste logado como SuperAdmin do subsite eu ainda conseguia ver a aba do Login Cidadão.

**Comment by thaisrigolon** [comment]
^

@marylly poderia responder, por favor?

**Comment by avaloni** [comment]
> Usuários com perfil Super Administrador e Administrador não precisam ver essa aba porque é uma configuração feita pelo SaaSadmin e não pode haver possibilidade de ser alterada por outros usuários impossibilitando o acesso à instalação.

Parece corrigido na branch **RC**, nem o usuário superAdmin da instalação principal nem um superAdmin do subsite conseguem ver a aba "Login Cidadão", podem verificar?

**Comment by marcus2703** [comment]
Quando puderem, coloquem a RC para utilizar o ID Cultura, pois no Fake a aba do LC não é exibida nunca. Ao menos era assim. Tanto que nem com o a role saasSuperAdmin consegui visualizar.

**Comment by thaisrigolon** [comment]
@GustavoVS e @vitor-kato poderiam colocar o ID Cultura no RC para testarmos essa issue?

**Comment by thaisrigolon** [comment]
Ok, homologado. Apenas usuários SaaSadm podem verificar:

![lc](https://cloud.githubusercontent.com/assets/18294515/26596572/9638b3aa-4545-11e7-8393-773d92b6170a.jpg)

**Comment by marcus2703** [comment]
Homologado
