### ISSUE TITLE
Erro exibição agentes modo lista

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#82]
Após atualização para V3 o modo lista dos agentes não está funcionando corretamente. Não mostra nenhuma informação, apenas caixas em branco.
Apenas quando habilitamos algum filtro que o mesmo começa a exibir os nomes de agentes e seus detalhes.

**Comment by thaisrigolon** [comment]
@marylly poderia ver esse bug, por favor? Ocorreu após a atualização para V3. Realmente, sem habilitar os filtros não aparece as informações dos agentes:

![1](https://cloud.githubusercontent.com/assets/18294515/22985596/06802326-f390-11e6-9170-55e4ae5766e2.png)

![2](https://cloud.githubusercontent.com/assets/18294515/22985608/0a5d5572-f390-11e6-9aeb-7a684f4cd3f1.png)

![3](https://cloud.githubusercontent.com/assets/18294515/22985616/0ebb5a38-f390-11e6-82dd-d3ce96708312.png)

**Comment by thaisrigolon** [comment]
@marcus2703 está ok em produção, acabamos de checar. Se fica em branco alguns agentes é porque não tem foto e descrição curta.
Poderia verificar?

**Comment by marcus2703** [comment]
De acordo Thaís.
Verifiquei que estes agentes são agentes do tipo pondo e entidade do Rede Cultura Viva.
Estes agentes recebem informações nos metadados.
