### ISSUE TITLE
Filtros - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#84]
Não é possível salvar nenhuma alteração nos filtros da instância em produção.

Ao tentar salvar o filtro de estado o sistema indica que "um erro inesperado aconteceu":

![1](https://cloud.githubusercontent.com/assets/18294515/23212192/5dac6f2a-f8e4-11e6-9ffc-4269fbbf3942.png)

![2](https://cloud.githubusercontent.com/assets/18294515/23212201/698c8a96-f8e4-11e6-9d5f-f1ee87589956.png)

**Comment by marylly** [comment]
Precisamos do log da aplicação @GustavoVS @thaisrigolon, porque não conseguimos reproduzir o problema.

**Comment by thaisrigolon** [comment]
Voltou a funcionar.
