### ISSUE TITLE
Criação de novo subsite - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#85]
@marylly, não é possível publicar um novo subsite, pois um "**erro inesperado aconteceu**". Não sabemos que erro ocorreu e não conseguimos criar uma nova instalação... a url está configurada e ainda não foi utilizada em nenhuma outra instância (pa.mapas.cultura.gov.br).

![1](https://cloud.githubusercontent.com/assets/18294515/23213355/654917d8-f8e9-11e6-8a54-e62dd99e8955.png)

**Comment by marylly** [comment]
Precisamos do log da aplicação @GustavoVS @thaisrigolon, porque não conseguimos reproduzir o problema.

**Comment by thaisrigolon** [comment]
Voltou a funcionar.
