### ISSUE TITLE
Entidades não aparecem - SaaS

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#86]
@marylly criamos duas instâncias (Pernambuco e Pará) e as entidades Eventos, Agentes, Espaços e Projetos não aparecem:

http://pe.mapas.cultura.gov.br/
![2](https://cloud.githubusercontent.com/assets/18294515/23304482/cfbc32f4-fa78-11e6-9d84-c48018cdd16d.png)

http://pa.mapas.cultura.gov.br/
![1](https://cloud.githubusercontent.com/assets/18294515/23304492/d9413c98-fa78-11e6-83e6-f20387407681.png)

Algo não foi habilitado? O que aconteceu?

**Comment by marcus2703** [comment]
![image](https://cloud.githubusercontent.com/assets/12901157/23306491/8e4ad1cc-fa82-11e6-809f-7f59052717f1.png)

Faltava apenas uma configuração.
