### ISSUE TITLE
Zoom Minimo Mapa

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#88]
A configuração do zoom mínimo não está funcionando no subsite.
Embora ela tenha sido devidamente configurada na edição do subsite:
![image](https://cloud.githubusercontent.com/assets/12901157/23319561/daef79dc-fab5-11e6-8011-390a0f808566.png)

Ela não está sendo exibida com o nível de zoom selecionado, bem como, não permite reduzir além do que está aparecendo.
![image](https://cloud.githubusercontent.com/assets/12901157/23319651/45fcf2ea-fab6-11e6-9519-21e3d8a9ed27.png)

**Comment by thaisrigolon** [comment]
@marylly poderia verificar, por favor? ^

**Comment by GustavoVS** [comment]
@marylly aceita esse PR assim que puder, por favor: https://github.com/hacklabr/mapasculturais/pull/1147
