### ISSUE TITLE
Criar selos

### ISSUE THREAD

**Issue by marylly** [culturagovbr/mapasculturais_descontinuado#9]
- [x] Somente admins podem criar selos;
- [x] Remover tipo de selo da tela;
- [x] Remover o IsVerified;
- [x] Colocar de volta os agentes relacionados na tela de edição do selo;
- [x] Remover seção de vídeos e galeria da tela de selos;
- [x] Incluir sessão de Downloads na tela de selos;
- [x] Aumentar o tamanho do avatar dos selos para 96px X 96px;
- [x] Campos de configuração do prazo de validade do selo;
- [x] Criar combobox para seleção da periodicidade da validade do selo;
- [x] Incluir campo na inscrição definindo se um selo será atribuído no momento da aprovação do inscrito ou na publicação dos resultados;
- [x] Geração de notificação comunicando quando um selo foi aplicado na inscrição;
- [x] Gerar e incluir as atualizações de banco de dados no db-updates do Mapas Culturais;
- [x] Incluir novo ícone dos selos do ambiente do Mapas Culturais.
- [x] Página das informações do selo aplicado a entidade com a funcionalidade de impressão de certificado;
- [x] Criação da migração do selo (isVerified) das bases existentes do mapas.

**Comment by marylly** [comment]
Selos disponibilizados para testes no servidor de testes.

**Comment by marylly** [comment]
- [x] Falta validação no campo de validade de selo, e não exibe mensagem avisando que precisa preencher.

CRIANDO UM SELO
- [x] preenchi propositalmente alguns campos com valores inválidos e não deu erro nenhum, mas não salvou. Depois disso, mesmo que eu corrigisse os campos, não salvava. Tive q recarregar e cadastrar de novo.

validade:
- [x] explicar q 0 é infinito
- [x] validação não está funcionando

Conteúdo
Precisa ter um valor padrão, e faltam algumas variáveis.
- [x] O nome do agente que concede o selo
- [x] O link para a verificação da autenticidade do selo
- [x] sealShortDescription

Na verdade, na minha opinião, poder configurar o texto é secundário.
- [x] valor padrão
  [sealName]
  [sealShortDescription]
  O [entityDefinition] [entityName] recebeu selo [sealName], concedido por [sealOwner].
  Selo concedido em [dateIni] e válido até [dateFin]. Para verificar autenticidade do selo visite [sealRelationLink]

APLICAR SELO 
- [x] colocar cursor pointer no mouseover do + e do selo pra aplicar

PÁGINA DO SELO (seal relation)
- [x] tá pedindo pra fazer login pra visualizar. deve ser aberta
- [x] Na verdade, essa página é pra ser praticamente a mesma coisa do que a "impressão do selo", só q com layout ali de página web. Ao invés de quebrar em duas seções, mostrando a descrição do selo, e depois o agente, colocar a foto do selo, o nome, e, embaixo, o texto configurado lá na hora q criou o selo.

CRIANDO PROJETO COM SELO
- [x] Estilo da modal que seleciona o selo tá zuado e aparecendo no lugar errado (ancorado no lugar errado)
- [x] botar estilo cursor poniter no + para adicionar selo e no selo pra selecioná-lo
- [x] tanto na hora de anexar o regulamento como na hora de criar um campo, ao dar ok na modal ela não sumia nunca. Salvei e recarreguei a página pra conseguir seguir adiante.

SE INSCREVENDO EM EDITAL COM SELO
- [x] Deu erro:
  Type: ErrorException
  Code: 2
  Message: Missing argument 3 for MapasCulturais\Themes\BaseV1\Theme::addSealsToJs(), called in /srv/master.map.as/mapasculturais/src/protected/application/themes/BaseV1/layouts/parts/singles/registration-edit--seals.php on line 6 and defined
  File: /srv/master.map.as/mapasculturais/src/protected/application/themes/BaseV1/Theme.php
  Line: 719

**Comment by GustavoVS** [comment]
Entidade Selo
- Visualização
  - [x] O Campos de Descrição Longa não aparece mesmo tendo sido preenchido
  - [x] Quando o campo de descrição curta é utilizado até o seu máximo o texto fica desconfigurado. Evidência: https://i.imgsafe.org/0a7ea69ea5.png
- Criação
  - [x] Ao tentar publicar um novo Selo sem o campo "Validade" preenchido, exibe uma mensagem "Erro inesperado" e não informa o campo que deve ser informado
  - [x] A opção "Adicionar avatar" não funciona [Incluído aviso que é possível incluir imagens ao registro após salvar o mesmo]

Relação com os Selos
- Visualização
  - [x] A opção "Selos Aplicados" é editavel antes de estar no modo de edição
  - [x] Ao Clicar em um Selo, não leva para a página do Sleo
- Criação
  - [x] Ao tentar adicionar um Selo a caixa de Selos desaparecem
- Edição
  - [x] O Selo é salvo antes de apertar no botão Salvar (O selo  não está vinculado com o botão salvar da edição da entidade)
  - [x] Após adicionar, excluir um Selo e tentar adicionar novamente, a caixa aparece desalinhada e não fecha mais se não houverem mais selos para adicionar. (Não consegui simular o desalinhamento, mas para o modal fecha ao clicar em "Fechar").
  - [x] Quando o Modal com os selos está aberto, ao clicar em outro controle de edição como Nome, Descrição.. o Modal não fecha.

**Comment by GustavoVS** [comment]
Documentação de Usuário para utilização dos Selos:
https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_user_seal.md
