### ISSUE TITLE
Erro exibição de eventos - Modo Mapa

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#91]
Quando visualizamos eventos no modo de exibição mapa, ao clicar no ícone do evento, ele fica com a mensagem de "obtendo resultados" sem mostrar os detalhes do mesmo.
A versão do mapas em produção está com este erro.

![image](https://cloud.githubusercontent.com/assets/12901157/23513093/ad077f70-ff41-11e6-9f7a-5f4921c52380.png)

**Comment by marcus2703** [comment]
Avaliar o Pull Request solicitado pelo @nidorx
https://github.com/hacklabr/mapasculturais/pull/1121

@marylly @GustavoVS @thaisrigolon

**Comment by GustavoVS** [comment]
@marylly esse PR https://github.com/hacklabr/mapasculturais/pull/1121 corrige essa issue e a #92 

Quando der aceita esse PR por favor?

**Comment by GustavoVS** [comment]
@marcus2703 pode validar, por favor?

**Comment by marcus2703** [comment]
Correção aplicada com sucesso.
TAG 3.0.7
