### ISSUE TITLE
Erro exibição agenda - Espaços

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/mapasculturais_descontinuado#92]
Quando clicamos na opção de agenda de um determinado espaço, o mesmo não exibe nada, mostrando apenas o ícone de processamento, sem finalizar.
Mesmo alterando as datas para datas que tenham algum evento, o mesmo mostra apenas o icone de processamento.

![image](https://cloud.githubusercontent.com/assets/12901157/23522148/aa2d3eba-ff60-11e6-97bb-b4879e8e498f.png)

Um erro inesperado aconteceu

exception 'ErrorException' with message 'array_intersect(): Argument 2 is not an array' in /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Repositories/Event.php:43
Stack trace:
0 [internal function]: Slim\Slim::handleErrors(2, 'array_intersect...', '/srv/mapas/mapa...', 43, Array)
1 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Repositories/Event.php(43): array_intersect(Array, '1,2,3,4,5,6,7,8...')
2 /srv/mapas/mapasculturais/src/protected/application/plugins/AgendaSingles/Plugin.php(34): MapasCulturais\Repositories\Event->findBySpace(Object(MapasCulturais\Entities\Space), Object(DateTime), Object(DateTime))
3 [internal function]: AgendaSingles\Plugin->AgendaSingles\{closure}('12002')
4 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(1243): call_user_func_array(Object(Closure), Array)
5 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(276): MapasCulturais\App->applyHookBoundTo(Object(MapasCulturais\Controllers\Space), 'GET(space.agend...', Array)
6 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(176): MapasCulturais\Controller->callAction('GET', 'agendaSingle', Array)
7 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Space), 'agendaSingle', Array, false)
8 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
9 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
10 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
11 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
12 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
13 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ErrorHandler.php(31): Slim\Middleware\MethodOverride->call()
14 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): MapasCulturais\Middlewares\ErrorHandler->call()
15 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
16 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
17 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(484): Slim\Slim->run()
18 /srv/mapas/mapasculturais/src/index.php(4): MapasCulturais\App->run()
19 {main}

**Comment by GustavoVS** [comment]
Essa issue é corrigida no Pull Request solicitado pelo @nidorx 
hacklabr#1121

@marylly @marcus2703

**Comment by GustavoVS** [comment]
@marcus2703 pode validar, por favor?
Ai já fecha essa issue e colocamos essa correção na próxima atualização.

**Comment by marcus2703** [comment]
Correção aplicada com sucesso.
TAG 3.0.7
