### ISSUE TITLE
Função getAdmins seleciona mais de um saasadmin para envio de email de denuncia

### ISSUE THREAD

**Issue by diegodorgam** [culturagovbr/mapasculturais_descontinuado#96]
getAdmins precisa selecionar apenas o email do admin do subsite para enviar a denuncia.

**Comment by rafaelchavesfreitas** [comment]
fiz uma nova tag **3.0.14** com esta correção e apliquei a correção nas branches **v3**, **rc** e **master**

**Comment by thaisrigolon** [comment]
Como já está na tag de produção, consideramos que está ok.

**Comment by diegodorgam** [comment]
só pra deixar uma lembrança, não sei se os guris ativaram as configurações de envio de e-mail na produção. Mas já passamos esse processo todo com a equipe da Hepta, qqr coisa o @marcus2703 monitora e se precisar de ajuda denovo pra configurar avisa a gente.
