### ISSUE TITLE
Tipologia "agentes individuais"

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais_descontinuado#99]
Os agentes individuais deveriam usar outra tipologia, que é o CBO (cadastro brasileiro de ocupações). Inclusive muitos dados que foram migrados do antigo RAC possuem essa informação salva no banco lá.
Hoje os agentes individuais são obrigados a preencher uma tipologia que é referente a coletivos e não faz sentido.

**Comment by leogermani** [comment]
Copiando o comentário original q deu origem a essa issue 
...
Essa é uma tarefa um pouco maior que seria legal ver se conseguirmo resolver. Algo que ficou incompleto ainda da primeira migração do SNIIC para o Mapas.

Colocamos no tema do MinC a tipologia de agentes. No entanto, colocamos apenas a tipologia de agentes coletivos.

Os agentes individuais deveriam usar outra tipologia, que é o CBO (cadastro brasileiro de ocupações). Inclusive muitos dados que foram migrados do antigo RAC possuem essa informação salva no banco lá.

E aí acontece que hoje os agentes individuais são obrigados a preencher uma tipologia que é referente a coletivos.. e não faz sentido.

Inclusive, resolvendo isso, a gente poderia incoroporar isso ao core do Mapas.

**Comment by GustavoVS** [comment]
@leogermani @marcus2703  a lista do CBO que vamos seguir é essa aqui? validar http://www.mtecbo.gov.br/cbosite/pages/downloads.jsf
Alguém do MinC precisa dar um "ok" em qual lista vamos usar?

Só pra registrar, as imagens mostram o comportamento atual em relação a tipologia dos agentes. Na segunda imagem, a lista deveria ser a do CBO:

![image](https://user-images.githubusercontent.com/7750643/36032769-2dbe108a-0d96-11e8-87df-e09b30504ea9.png)

![image](https://user-images.githubusercontent.com/7750643/36032834-5b00472a-0d96-11e8-80ec-02bc1e6e371e.png)

**Comment by vnmedeiros** [comment]
boa tarde, 
Realizei as alterações sugeridas (branch  [feature/tipologia](https://github.com/culturagovbr/mapasculturais-baseminc/tree/feature/tipologia)), dessa forma agora exitem duas janelas, uma para cada tipologia:

coletiva
![coletivo](https://user-images.githubusercontent.com/1179250/37365328-f05d6a06-26db-11e8-99fc-1203cb423a9b.png)

individual
![individual](https://user-images.githubusercontent.com/1179250/37365338-f92bf616-26db-11e8-8f10-b691db03bbaf.png)


Uma questão, O que deve ser feito com o agentes já cadastrados na base que utilizaram a tipologia errada?
